#adventofcode2017
#crushallhumans
#day7
#20171207


import sys
from anytree import Node, RenderTree

tree = []
tree.append(['pbga',66])
tree.append(['xhth',57])
tree.append(['ebii',61])
tree.append(['havc',66])
tree.append(['ktlj',57])
tree.append(['fwft',72, ['ktlj','cntj','xhth']])
tree.append(['qoyq',66])
tree.append(['padx',45, ['pbga','havc','qoyq']])
tree.append(['tknk',41, ['ugml','padx','fwft']])
tree.append(['jptl',61])
tree.append(['ugml',68, ['gyxo','ebii','jptl']])
tree.append(['gyxo',61])
tree.append(['cntj',57])

def get_puzzle_input():
    tree = []
    tree.append(['navfz',187, ['jviwcde','wfwor','vpfabxa']])
    tree.append(['adtfnx',74])
    tree.append(['endsg',33])
    tree.append(['wcswjri',228, ['jcnfvhv','yprbzn']])
    tree.append(['gvfys',83])
    tree.append(['vcedn',12462, ['ypmviuh','vobydav','axkokcp','ntgxar','keuxhfl']])
    tree.append(['mmfkf',94, ['mubgcn','zxdcbk']])
    tree.append(['jgmxdc',79, ['zvmzo','wmpeyz']])
    tree.append(['bxyfc',79])
    tree.append(['thgwtgt',129, ['zhjvk','ocxox']])
    tree.append(['nrvdexu',48])
    tree.append(['lcdnv',246, ['hksnbzc','texmxw']])
    tree.append(['pdiie',77])
    tree.append(['eowfj',90])
    tree.append(['gzchiz',68])
    tree.append(['ulurun',60])
    tree.append(['ckavnt',68, ['umheofb','blsyfi','qijkhbz','ithmj']])
    tree.append(['wjbbg',59])
    tree.append(['nvwje',98])
    tree.append(['rhxhixx',62])
    tree.append(['dautk',89])
    tree.append(['ovxjjgk',45])
    tree.append(['iimosg',6])
    tree.append(['dxmqgds',238, ['tbmyzr','itmcnzc']])
    tree.append(['hspiay',42])
    tree.append(['qvymrle',166, ['daeabq','eskrg']])
    tree.append(['qrtvd',64])
    tree.append(['dhanhrw',82])
    tree.append(['zikfenq',10])
    tree.append(['ozrban',76])
    tree.append(['wjbpo',1502, ['clhgsb','hypdv']])
    tree.append(['utpjye',43])
    tree.append(['dkaaia',96])
    tree.append(['ddotjil',6045, ['ptagt','ikrdl','swotlas','ajnug','gphzut','xosbped','rtiwxq']])
    tree.append(['vuskd',68, ['vcbywzm','icqjwqy','maxjejh','unminnt','sinsn','tvvqdps','fanqwrt']])
    tree.append(['hlhhfys',84])
    tree.append(['bwomuu',65])
    tree.append(['qokveql',19])
    tree.append(['jbxmsp',20])
    tree.append(['xcmjo',87])
    tree.append(['pocpbk',13])
    tree.append(['ifbpc',165, ['jpfnrj','yioozfb']])
    tree.append(['cqssrlq',30])
    tree.append(['qerpj',187, ['ajcozt','bocgrjf']])
    tree.append(['zicqv',35])
    tree.append(['cqgumz',47])
    tree.append(['rwmqr',385, ['endsg','ivcasrz']])
    tree.append(['sctwm',354])
    tree.append(['pmmzezq',32, ['llqdavt','ymyhnhz']])
    tree.append(['dxgmc',8])
    tree.append(['szfroua',32])
    tree.append(['otdtras',37])
    tree.append(['qmnsyex',427, ['ucytsw','fnnxu','ntiulub','dbpvy']])
    tree.append(['qsniae',199, ['uibkcpe','stwgbsz']])
    tree.append(['nrrops',85])
    tree.append(['gasjpi',95])
    tree.append(['niziq',1492, ['gcbftk','vxzlg','gxrxqy']])
    tree.append(['vpkkrb',155, ['jwfem','rhxhixx']])
    tree.append(['unsfg',97])
    tree.append(['qkfeemt',88])
    tree.append(['yycjr',265, ['fipbn','vgyzi','btczn']])
    tree.append(['tijgqz',391])
    tree.append(['vuujvxl',27, ['dnwlbpp','giwtr']])
    tree.append(['vikokw',77, ['qifoire','djshoi']])
    tree.append(['ltseb',200, ['pqmsk','seciy','ybvbei']])
    tree.append(['khtlck',82])
    tree.append(['elgpli',87])
    tree.append(['kkyycy',34, ['cncssy','oajts','oufwlo','qxnuybx']])
    tree.append(['hisqsfr',82])
    tree.append(['cwstpsc',17])
    tree.append(['frmsjzw',35])
    tree.append(['pgxppw',58])
    tree.append(['vkbeys',82])
    tree.append(['wjswjjk',194])
    tree.append(['fjxoyo',15])
    tree.append(['cqlwmo',98])
    tree.append(['tdnsh',350, ['ghfcln','flmfqb']])
    tree.append(['czhcaiz',71])
    tree.append(['daeabq',62])
    tree.append(['nbxyhp',55])
    tree.append(['insxss',60])
    tree.append(['epvrmk',21])
    tree.append(['tlxbs',13])
    tree.append(['izhrthy',59])
    tree.append(['kipoq',15])
    tree.append(['xuxxxmh',11])
    tree.append(['qbnzq',59])
    tree.append(['njfrq',220, ['mxjxqd','rdhwksn']])
    tree.append(['mzgecu',170, ['eelypm','grcoom']])
    tree.append(['wzncmog',42, ['eyxcrae','gxvbg','ikzndn','otxum']])
    tree.append(['dkzjztp',47])
    tree.append(['wgnjhy',34])
    tree.append(['uubtu',164, ['itozwej','vxbgygu']])
    tree.append(['dcsbhra',51])
    tree.append(['mfmnp',68])
    tree.append(['ppjmufh',20])
    tree.append(['rjich',28])
    tree.append(['edyopxe',56])
    tree.append(['kjqwac',61, ['esnxvu','kzbfyep','ammlo','bedla']])
    tree.append(['fkthtxx',60])
    tree.append(['tslgtw',13])
    tree.append(['vxbgygu',73])
    tree.append(['szkcigt',102, ['lnmixf','zjgflu','bemdu','fmzdg']])
    tree.append(['niubs',52])
    tree.append(['clpswz',66])
    tree.append(['mngbghh',90])
    tree.append(['anongb',158, ['yimofqp','qnqir']])
    tree.append(['pswzpo',88, ['mfbagfq','ncrtwlq','mfoinlm','lrrdrb']])
    tree.append(['rdgfmzc',51])
    tree.append(['awquent',203, ['kqnxr','oheqyl']])
    tree.append(['eskrg',62])
    tree.append(['hpvubeg',76, ['xkhavpc','ochboo','zwrhhqv','mhvpzbf']])
    tree.append(['upfebsl',76])
    tree.append(['bwgyj',114, ['apmbdgn','fgqrqj']])
    tree.append(['tfwgxrq',358])
    tree.append(['vlbzvxp',93])
    tree.append(['vbnyv',76])
    tree.append(['ivztoux',26])
    tree.append(['crstch',124, ['fudyri','rkkuowi','jlekzzy']])
    tree.append(['jnhjfg',81])
    tree.append(['muhtyvc',145, ['qyfwbx','otdtras']])
    tree.append(['ywnbh',98, ['epufxrr','ehurzzp','ecyhx','zbuzek']])
    tree.append(['gcbftk',315])
    tree.append(['bxnmwa',81, ['krcry','kdrfg','ansxn','plygyiz']])
    tree.append(['mhuwxy',40, ['ybuimo','vtuldjj']])
    tree.append(['mgpvr',74])
    tree.append(['fnxgxy',89])
    tree.append(['fqmyeu',78])
    tree.append(['cmdkcy',40])
    tree.append(['yxgken',192, ['pivhdjq','gynyaeu','ahlklti','moxkfxc']])
    tree.append(['wvfahid',87])
    tree.append(['eelypm',12])
    tree.append(['rernf',11, ['okncqru','xtbfzkp','rcgbe','nuwcul']])
    tree.append(['uogjfe',102, ['eiqee','swimi']])
    tree.append(['fwsxuc',147, ['coekrtq','fltcx']])
    tree.append(['eyxcrae',67])
    tree.append(['vpfxqm',98])
    tree.append(['mopjtoj',99])
    tree.append(['vbnbtrd',95])
    tree.append(['ztioqqe',83, ['uqbcgt','btnoqzd','kddqe','sgosmil']])
    tree.append(['oqvygul',52])
    tree.append(['lqqdqgl',55])
    tree.append(['hdbck',101, ['ayiitk','xakrpew']])
    tree.append(['ohdtu',29])
    tree.append(['nzcwei',54, ['pgwquco','bebulic']])
    tree.append(['kqkarm',27])
    tree.append(['qotrtx',16])
    tree.append(['ashso',637, ['hjhcc','xouweh','fwmowjn','vgpxi','sfovf']])
    tree.append(['gfagn',59])
    tree.append(['vqrxmf',33])
    tree.append(['umlcaag',353])
    tree.append(['fxludfk',115, ['eajkem','ettrul']])
    tree.append(['plkvbhb',65])
    tree.append(['uwjqmt',40])
    tree.append(['izzpwi',37])
    tree.append(['thtpl',93])
    tree.append(['mohkqjm',6])
    tree.append(['kfrwdp',57])
    tree.append(['xzghryr',44])
    tree.append(['csrpgne',84])
    tree.append(['uapxgoj',94, ['jbxmsp','iameqxg','zvihzi']])
    tree.append(['vifsucu',239, ['aveyaj','xsxubhv','zanvcz']])
    tree.append(['jhdhgp',446, ['etfguf','jxdpg']])
    tree.append(['oujsw',38, ['nalao','gzchiz','qtoqshz']])
    tree.append(['dporqyl',237, ['jjkrqj','zdtwo']])
    tree.append(['xdcuy',138])
    tree.append(['agczxc',54])
    tree.append(['muczne',9])
    tree.append(['qcrztf',27])
    tree.append(['eajkem',65])
    tree.append(['zvofir',68])
    tree.append(['rmjchv',45, ['bqlsax','hrjkg','smjdft','rbubdz']])
    tree.append(['auhjkqg',58])
    tree.append(['skcvg',287, ['udpkm','bltzxtt','rkjces','fbgohwn']])
    tree.append(['ikmblf',20])
    tree.append(['tkdal',46])
    tree.append(['hyagspc',82])
    tree.append(['kggin',96])
    tree.append(['mxbsj',59])
    tree.append(['sguuvok',199, ['bbjxvr','drtzf','lyopa','nlewje']])
    tree.append(['uuzaefz',29])
    tree.append(['zsxjki',86, ['ygcjbtt','ezghsl','unsfg','npabeh']])
    tree.append(['esikob',281, ['runxvuj','pgjgnaz']])
    tree.append(['ybtkcry',198, ['kmurqns','dzimoh']])
    tree.append(['qsprrb',50])
    tree.append(['kcpmu',32])
    tree.append(['giwtr',30])
    tree.append(['fcicnl',302, ['wpvpo','wtcxhy']])
    tree.append(['olqpfvj',75])
    tree.append(['povpspa',32])
    tree.append(['bmozv',66])
    tree.append(['uifttbe',76])
    tree.append(['exgnitf',95])
    tree.append(['pifrouj',137, ['solzny','qvzmtfl']])
    tree.append(['acdth',26])
    tree.append(['pvbqjz',45])
    tree.append(['dgzfep',1135, ['tdjqll','uyowaek','mbkvojh','mbpmp','rlvog']])
    tree.append(['gaiqlzf',106, ['pmbfnsr','insxss']])
    tree.append(['jjwoc',1785, ['vwmgmf','vqenunc','vrbhapd','sraenhx','bwatw']])
    tree.append(['qpdxpob',46])
    tree.append(['tyfdd',26])
    tree.append(['zslja',85])
    tree.append(['vmlltwb',23, ['jrxjdr','xuglsp']])
    tree.append(['pdzqzk',89])
    tree.append(['lzrav',78])
    tree.append(['abftzdj',72])
    tree.append(['kihgxqn',205, ['wxyaro','ivbzfo','hnhcg']])
    tree.append(['qsilzzo',146, ['hjzjhbc','cfbxssz']])
    tree.append(['xvlxy',77, ['jcrly','esikob','cxmrla','pdmci','avefgw']])
    tree.append(['msvagxz',106, ['dngxvvl','fhyaa']])
    tree.append(['bawokn',45])
    tree.append(['qryoc',79])
    tree.append(['abpnn',85])
    tree.append(['pvrff',74])
    tree.append(['beocgcy',7, ['dmyoiho','eybms']])
    tree.append(['vrxhty',91])
    tree.append(['pqbatbl',279, ['ivztoux','czifkmc','tyfdd','ucchch']])
    tree.append(['cbeoz',44])
    tree.append(['fqzleh',88])
    tree.append(['uihio',40])
    tree.append(['lvblzvy',6])
    tree.append(['utgpz',81, ['aqvoo','dtjjjie']])
    tree.append(['gmlbsa',64, ['zslja','zpzfwgd','bmjxtay','pvcbg']])
    tree.append(['ncgmykk',1128, ['nywbm','nzcwei','yhwnho']])
    tree.append(['opbvo',18, ['hppnn','llzhmol','tzhxfhh','svsfd','xjqhzdl','tjcmctp','njfrq']])
    tree.append(['hcpnjd',6])
    tree.append(['xddgt',69])
    tree.append(['jowbm',53])
    tree.append(['ertcv',28])
    tree.append(['btrafox',1442, ['hndngj','vjnwg','qcispj']])
    tree.append(['evrgojz',190, ['ljiem','vlbzvxp']])
    tree.append(['xbipb',72])
    tree.append(['ecyhx',50])
    tree.append(['usrgham',53])
    tree.append(['czifkmc',26])
    tree.append(['honkhjh',73])
    tree.append(['dworlrf',221, ['djswc','qdymjur']])
    tree.append(['mlojggk',95])
    tree.append(['mpiiw',186, ['sjkpb','vbihwha','vbcwp','khdjiyr']])
    tree.append(['ajcozt',16])
    tree.append(['nqagpl',24])
    tree.append(['pmbfnsr',60])
    tree.append(['kepyvd',69])
    tree.append(['vztbk',76])
    tree.append(['tgeefln',30])
    tree.append(['opwdy',142, ['rjohk','apkxv']])
    tree.append(['iameqxg',20])
    tree.append(['hbozd',83, ['lgkbqm','ranrjjb','vioxr']])
    tree.append(['ozdamth',290, ['qcguyb','zaciz']])
    tree.append(['pqmxcxl',12, ['dgcwsz','omqgks','abbgnrq','kimml']])
    tree.append(['ikrdl',478, ['gkgbww','pjtywfh','orecwx','goyyy']])
    tree.append(['drcwwke',1141, ['tabeoxr','uapxgoj','hyrbb']])
    tree.append(['ddqvjcz',239])
    tree.append(['ccjrwmk',56, ['qewogca','qrybtpr']])
    tree.append(['zezfk',231])
    tree.append(['mmjuj',8])
    tree.append(['dxogq',246, ['lhxrely','iimosg']])
    tree.append(['hnuck',10755, ['bbshy','fffuhf','qnaxzd','kcdvc']])
    tree.append(['btegf',27])
    tree.append(['qgbbnl',22, ['ozczna','lyilhws','vzamfb','tehnz']])
    tree.append(['jhrqcd',83])
    tree.append(['ttkwrfr',366, ['btegf','afjclgu','uqmjp','jixtgz']])
    tree.append(['tpzzyfa',11614, ['ighxv','drcwwke','rernf']])
    tree.append(['dppsv',179, ['josdymn','nguoj']])
    tree.append(['shryh',98])
    tree.append(['voeqqmw',72])
    tree.append(['pqmsk',21])
    tree.append(['ucchch',26])
    tree.append(['ahvumy',62, ['zunvrg','zzsjfh','osqvb','kcqkcz']])
    tree.append(['mtopo',156, ['xiollwu','nznkw']])
    tree.append(['qvujwr',85])
    tree.append(['nalao',68])
    tree.append(['ccikbql',74])
    tree.append(['illptaw',90])
    tree.append(['mweaj',75])
    tree.append(['vcbywzm',114, ['saalu','ipmtfwk']])
    tree.append(['qifoire',59])
    tree.append(['gfhpte',47, ['mcqabbl','vazzmfm','pruiu','rrymbf']])
    tree.append(['adyard',54])
    tree.append(['kwetye',65])
    tree.append(['btzchz',134, ['rmczuu','fglno','mnqvu']])
    tree.append(['oulrj',17])
    tree.append(['wndcqx',72])
    tree.append(['khyng',94])
    tree.append(['xkmzwq',77, ['qhrye','kdzri','nyyqkh','vumehdr','bqbsz','lcidw','kyubds']])
    tree.append(['wcfykrj',67])
    tree.append(['lhgstq',193, ['uxlbo','tsrgg']])
    tree.append(['szzqsmn',147, ['aufrup','burxc']])
    tree.append(['cncssy',48])
    tree.append(['dbpvy',6])
    tree.append(['iqemusp',314])
    tree.append(['ulgox',80])
    tree.append(['ffkrppv',187, ['oulrj','cwstpsc']])
    tree.append(['bxcfhgy',28])
    tree.append(['zkzcu',55])
    tree.append(['kxphfg',70])
    tree.append(['yrkcwxr',46])
    tree.append(['vgpxi',304, ['ertcv','mzxret']])
    tree.append(['vrvhkwg',75])
    tree.append(['gzuvfqc',186, ['kvmhp','niubs','fbnge']])
    tree.append(['mtoet',127, ['uokbqcq','yrkcwxr']])
    tree.append(['wltqbe',19])
    tree.append(['ighxv',363, ['prvxtd','iikdtt','wzncmog','gxuohw']])
    tree.append(['gjowlue',588, ['ifwxdp','vxbrvx','tzgilw','brupv']])
    tree.append(['vitgymq',145, ['mqgxx','iqxqmc','wvfdz']])
    tree.append(['sbjuka',89])
    tree.append(['dgcwsz',138, ['tybkxd','ppgnqem','kcpmu','zpghac']])
    tree.append(['pnnwkn',19, ['jgcfh','plptt','uxcmj','fiaepdw','ibkwb','lfklsmy','swdcc']])
    tree.append(['vxgexz',128, ['qftvm','tjngq']])
    tree.append(['ezrvccj',52])
    tree.append(['praqutu',63])
    tree.append(['fuctso',91, ['dphyg','vszgnbj','zfjcea','ukdaa','myecan','hosih','mljbkl']])
    tree.append(['ynleow',72])
    tree.append(['cwrmfzk',29])
    tree.append(['sruad',66])
    tree.append(['ettrul',65])
    tree.append(['vvsev',346, ['hwtudr','bptud','qekqaz']])
    tree.append(['eolje',67])
    tree.append(['vxwudy',85])
    tree.append(['fukzhnf',70, ['tdwgne','xkoyskt']])
    tree.append(['hyzcrj',65, ['fhtkd','ljmmpot']])
    tree.append(['carik',11])
    tree.append(['djswc',12])
    tree.append(['obohol',57])
    tree.append(['solzny',54])
    tree.append(['pqkvbwc',39])
    tree.append(['phcqjf',90])
    tree.append(['btczn',15])
    tree.append(['asnxgw',23])
    tree.append(['oupnrtc',21])
    tree.append(['ylunw',28])
    tree.append(['fhyaa',60])
    tree.append(['tcyvkaf',144, ['hspiay','tviveza']])
    tree.append(['qtoqshz',68])
    tree.append(['pnmirw',51])
    tree.append(['mkxgloe',53])
    tree.append(['lysjk',373, ['nqagpl','bwuyaa']])
    tree.append(['tujlwef',125])
    tree.append(['zfeudr',14, ['uylkjb','jroccc','zzdnotv','palhxo']])
    tree.append(['cxmrla',231, ['enant','gvfys']])
    tree.append(['bbccojb',88])
    tree.append(['kpgyfzy',57])
    tree.append(['qzgapj',31, ['ppgep','bhmbpei','odpwrq']])
    tree.append(['phawl',82])
    tree.append(['etfguf',14])
    tree.append(['dapiuh',65])
    tree.append(['mhvpzbf',91])
    tree.append(['unzfplq',1607, ['ifbpc','vmlltwb','lftee','fklkx','fnvqq','wgrdy']])
    tree.append(['yjbucib',86])
    tree.append(['ycjdb',36])
    tree.append(['uqbcgt',2192, ['ctaxhl','irgxwel','varne']])
    tree.append(['xauvth',98])
    tree.append(['fyijlyp',196])
    tree.append(['grcoom',12])
    tree.append(['epckorn',10])
    tree.append(['roihpx',589, ['qffyap','sabtf','ubsxskk','uehaezr','yuhoog','awquent']])
    tree.append(['kqrpmtu',79])
    tree.append(['iljmpy',1152, ['kxezytz','uzylso','pifrouj']])
    tree.append(['btoap',47, ['ctixwt','jhylsh','cyrnme','zezfk']])
    tree.append(['wlnvlvv',14])
    tree.append(['rrswfd',62])
    tree.append(['kyubds',53, ['juljpnm','dapiuh','tqpoo','kwetye']])
    tree.append(['veeafpm',157, ['nvwje','mfblbq']])
    tree.append(['woujjmo',59])
    tree.append(['dtvjbm',324, ['uihio','ybjde']])
    tree.append(['srdaso',45])
    tree.append(['dyjywtj',67])
    tree.append(['ntogi',230, ['biyngj','lwwuq']])
    tree.append(['vntnpm',99])
    tree.append(['eyyypjs',86])
    tree.append(['uqmjp',27])
    tree.append(['ofnfoy',75])
    tree.append(['fhxynme',53])
    tree.append(['ppgep',65])
    tree.append(['qiwpw',37, ['kfvkh','ahcqquf']])
    tree.append(['sjkpb',31])
    tree.append(['hdevhyk',188, ['tzymfw','sscdb']])
    tree.append(['sgosmil',1704, ['ffdwtz','qsniae','vmypqee','vayfab','dxbjv','ffkrppv','gqjmp']])
    tree.append(['kmpxcdm',38, ['vkfupb','lbzwb','bgteja','pgebb','mdipga','bjkfclz','zuypk']])
    tree.append(['nxnvm',162, ['vqrxmf','bgelipj']])
    tree.append(['krommni',51, ['xdffsw','iuthq']])
    tree.append(['wxakfgm',246, ['khlwul','pkmsa']])
    tree.append(['ewflis',66])
    tree.append(['josdymn',98])
    tree.append(['nlonnkx',255, ['ohdtu','noftq']])
    tree.append(['xboup',12, ['knegpur','khtlck','axees']])
    tree.append(['kpdnx',313])
    tree.append(['nlewje',9])
    tree.append(['hpygxqx',57])
    tree.append(['rtvetjy',124, ['qcrztf','nwemm']])
    tree.append(['rbubdz',77])
    tree.append(['maxjejh',208])
    tree.append(['nnfwd',268, ['abftzdj','voeqqmw']])
    tree.append(['knegpur',82])
    tree.append(['gdhqehb',89])
    tree.append(['kasjbl',195])
    tree.append(['bbjxvr',9])
    tree.append(['fhoohx',76, ['psfmvag','clxelo']])
    tree.append(['xsxubhv',75])
    tree.append(['aqiyzjv',20])
    tree.append(['myuqc',98, ['ebchb','gzzodai','uqvkdd','orrks']])
    tree.append(['hayenti',46])
    tree.append(['udpkm',41])
    tree.append(['sysqfo',45])
    tree.append(['tzpoh',38])
    tree.append(['vfisys',53])
    tree.append(['spznevr',80])
    tree.append(['jiwmrx',30])
    tree.append(['iapwe',64])
    tree.append(['phkek',45])
    tree.append(['tehnz',89])
    tree.append(['vfrbqk',47])
    tree.append(['mbuhvxk',104, ['pjdbaq','bmpdcge']])
    tree.append(['priuy',87])
    tree.append(['rvtdj',23])
    tree.append(['prvxtd',120, ['ziuhn','exgnitf']])
    tree.append(['ffqjbfe',102, ['hbtzel','xjcil']])
    tree.append(['coekrtq',13])
    tree.append(['ooike',38])
    tree.append(['xosbped',446, ['llpwnd','upzddgb','yvaua','qfpunan']])
    tree.append(['fjtqmt',35, ['dkaaia','tllopby']])
    tree.append(['sraenhx',210, ['sjxpoy','xiriq']])
    tree.append(['wnvqy',15])
    tree.append(['zvihzi',20])
    tree.append(['tnutmxv',264, ['eewro','gwvwgyr','yntvfk','zvhpm']])
    tree.append(['ahlklti',15])
    tree.append(['xixzhx',89])
    tree.append(['qabjz',98, ['pzjusto','uwjqmt','ndynhq','jbvxahe']])
    tree.append(['zcruqaw',37])
    tree.append(['rsqeoo',30])
    tree.append(['pvtbmzi',302, ['ppjmufh','hhxwcq']])
    tree.append(['tabeoxr',154])
    tree.append(['xdsctl',7, ['wvfahid','elgpli','oqjdqhz','uwtjv']])
    tree.append(['qftvm',55])
    tree.append(['lqgal',317, ['uivra','izzpwi']])
    tree.append(['puhghe',270, ['leokcd','vkbeys']])
    tree.append(['gxuohw',154, ['fqmyeu','ygjlqcg']])
    tree.append(['kimml',54, ['yupgfp','kfrwimb','utcyzg','fhxynme']])
    tree.append(['wvfdz',92])
    tree.append(['dxhgr',69, ['hlylkh','higxu']])
    tree.append(['sflycrq',56])
    tree.append(['osqvb',62])
    tree.append(['fzedbkl',142, ['lncvfka','bcylzy']])
    tree.append(['burml',360, ['gorrq','zbodcwy','eecmcs','ydgsome','pybcu','xdsctl']])
    tree.append(['upzddgb',95, ['jauss','vchbwy']])
    tree.append(['gigmx',12])
    tree.append(['mfblbq',98])
    tree.append(['fopaifs',89])
    tree.append(['jgysg',140, ['jyuiboq','dywaqyt']])
    tree.append(['stwgbsz',11])
    tree.append(['ochboo',91])
    tree.append(['ginbdt',83])
    tree.append(['bdbaph',82])
    tree.append(['sxmobi',96])
    tree.append(['zqfkx',10])
    tree.append(['tkcqnb',59])
    tree.append(['yorumsq',181, ['qokveql','clskgfl']])
    tree.append(['rilgrr',75761, ['ztioqqe','trukr','nfxyklo']])
    tree.append(['kaezunt',28])
    tree.append(['otfbit',1257, ['aptjv','gpiew','vuxruoi','xjbkl','arxmlc']])
    tree.append(['pyvum',21])
    tree.append(['utpfhue',88])
    tree.append(['obbwoe',38])
    tree.append(['ruxlsl',76])
    tree.append(['jlekzzy',24])
    tree.append(['dnwlbpp',30])
    tree.append(['tibjuc',11])
    tree.append(['zgvhx',70])
    tree.append(['ehurzzp',50])
    tree.append(['fgqrqj',98])
    tree.append(['zokot',238, ['rsqeoo','zdrfpo']])
    tree.append(['uxcmj',267, ['utpjye','tacjmyy']])
    tree.append(['sabtf',19, ['vztbk','xjzzeu','skmqfy','uicqk']])
    tree.append(['tviveza',42])
    tree.append(['etlozv',76])
    tree.append(['znqtjeb',85])
    tree.append(['eveeynr',380, ['emknkrh','ztfug']])
    tree.append(['ffdwtz',185, ['dwhpsh','ufjnfv']])
    tree.append(['vzttjf',21])
    tree.append(['vkfupb',93, ['adtfnx','aqkshy','dugvl']])
    tree.append(['iecpcid',20])
    tree.append(['zanvcz',75])
    tree.append(['spiel',126, ['kpxbfji','ynnqnnu']])
    tree.append(['rmczuu',60])
    tree.append(['dfqzdr',44])
    tree.append(['ppwgp',1776, ['vxgexz','frhpgy','gdjplif']])
    tree.append(['cjhaq',82])
    tree.append(['bbelj',48])
    tree.append(['kyofjtt',45])
    tree.append(['wvpurkk',24])
    tree.append(['xhmwo',49, ['hnpbcb','wqvjpwa']])
    tree.append(['qvzmtfl',54])
    tree.append(['pdmci',307, ['bawokn','vesets']])
    tree.append(['zvvyl',71])
    tree.append(['kflwup',78])
    tree.append(['hjhcc',210, ['ofnfoy','icwxs']])
    tree.append(['uxlbo',85])
    tree.append(['rskvj',85])
    tree.append(['yqznxzs',86, ['tdsaa','sflycrq','khzoaxo','iwhdp']])
    tree.append(['jmxvth',10])
    tree.append(['cnmxf',68])
    tree.append(['wtcxhy',71])
    tree.append(['micap',79])
    tree.append(['vdmtlr',332, ['cqssrlq','jiwmrx']])
    tree.append(['horvahx',41])
    tree.append(['pksuyfu',57])
    tree.append(['sjpywxy',45])
    tree.append(['moxkfxc',15])
    tree.append(['ppmiyqf',41])
    tree.append(['ezaywf',78])
    tree.append(['yhwnho',92, ['pngigbs','xewab']])
    tree.append(['uwtjv',87])
    tree.append(['gjxrim',34])
    tree.append(['ssebu',47])
    tree.append(['fiiscny',89])
    tree.append(['rktbwod',268, ['wtgjv','rrswfd']])
    tree.append(['oocst',98])
    tree.append(['ubiyjs',35])
    tree.append(['qcispj',179, ['ktvub','qhduwgb']])
    tree.append(['zxuigx',11])
    tree.append(['mcgydbg',25])
    tree.append(['ajxbw',12])
    tree.append(['omqgks',74, ['gbxvor','uczsgkq','agrscit']])
    tree.append(['hvngmr',49])
    tree.append(['jkkmv',36])
    tree.append(['nxdselb',47])
    tree.append(['lymfce',47])
    tree.append(['hrqdm',72])
    tree.append(['iodeix',157, ['ikmblf','ichmv','gvqpxq']])
    tree.append(['ixkdgf',49])
    tree.append(['kbxmmw',13])
    tree.append(['nqtrrnh',235])
    tree.append(['meddd',53])
    tree.append(['yntvfk',5])
    tree.append(['pbizn',36])
    tree.append(['ctwtm',48])
    tree.append(['otxilwl',74])
    tree.append(['aaydbfp',41])
    tree.append(['zndohw',286, ['ylrftrl','qpdxpob']])
    tree.append(['wuqyrfk',189])
    tree.append(['jndpmw',43, ['yjlat','cumfazk']])
    tree.append(['hkauzoo',122, ['kkvxx','gjxrim','qnmlqy']])
    tree.append(['aqvoo',91])
    tree.append(['utmatrv',314])
    tree.append(['qhduwgb',44])
    tree.append(['sjvozur',45])
    tree.append(['bgcudvy',83])
    tree.append(['khaofpf',6])
    tree.append(['rgnnme',65, ['xrktj','nccozmr']])
    tree.append(['twwimz',164, ['jwdlpw','emjkbw','jmxvth']])
    tree.append(['lnmixf',55])
    tree.append(['hhonck',94, ['wstoc','zvvyl','zhkwxu','czhcaiz']])
    tree.append(['zmyeh',54])
    tree.append(['odlntvv',1699, ['xvsnmmx','heradq','rmjqnz']])
    tree.append(['fkdnk',24])
    tree.append(['ukdaa',162, ['kiadzi','tlxmg','mcqbzy','txvuo']])
    tree.append(['tvvqdps',28, ['oxzwlk','zajkvp']])
    tree.append(['kgarj',44])
    tree.append(['qqomkf',84, ['gvuech','ctwqys']])
    tree.append(['belfq',79, ['yknoisw','ezaywf','gyftdi','ssurqjb']])
    tree.append(['ulwtqfp',95])
    tree.append(['dmyoiho',91])
    tree.append(['jborbj',95])
    tree.append(['vtuldjj',47])
    tree.append(['utcyzg',53])
    tree.append(['sqwjo',60])
    tree.append(['tdhba',54])
    tree.append(['vayfab',29, ['vqwptq','nwptea']])
    tree.append(['fksbg',80])
    tree.append(['zlrfy',70])
    tree.append(['sjxpoy',5])
    tree.append(['oswlpi',89])
    tree.append(['lvrqmv',78, ['ceypzh','geygl']])
    tree.append(['vwzwnip',96, ['hlhvabs','udqaee']])
    tree.append(['njusfd',77, ['ctwtm','ivgdluw','lunozxs']])
    tree.append(['zksrdel',80])
    tree.append(['slhqnia',65])
    tree.append(['nbguuj',524, ['ccqfrc','xdcuy','oieqvtt','mbuhvxk']])
    tree.append(['ztfug',47])
    tree.append(['juljpnm',65])
    tree.append(['onjgrby',396, ['mfzhe','kwibs']])
    tree.append(['ptagt',1325, ['vuujvxl','sdskev','snlcnb']])
    tree.append(['kxsxtd',59])
    tree.append(['rkyrvy',14, ['mweaj','vrvhkwg','vcjjb']])
    tree.append(['zvrvvky',35])
    tree.append(['mmjuyat',69])
    tree.append(['xiriq',5])
    tree.append(['ryluuhv',72])
    tree.append(['tyxuz',45])
    tree.append(['dfcpcm',184, ['obbwoe','ixwrmp']])
    tree.append(['rvtwdl',29, ['gttojem','wkvve']])
    tree.append(['aveyaj',75])
    tree.append(['ylrftrl',46])
    tree.append(['nbuie',31])
    tree.append(['xdffsw',99])
    tree.append(['kqnxr',60])
    tree.append(['wjpdd',73])
    tree.append(['bxpmf',94])
    tree.append(['rlvog',160, ['gasjpi','dhglkvc']])
    tree.append(['skmqfy',76])
    tree.append(['mghjs',188, ['dcsbhra','gohsqql','wirnc','hlseh']])
    tree.append(['wlaym',11043, ['arldq','klvoil','pqmxcxl','kekcm','nbguuj']])
    tree.append(['ajnkrwf',38, ['mlojggk','ianvxjm']])
    tree.append(['qcodb',45])
    tree.append(['jacnhvn',16])
    tree.append(['ljiem',93])
    tree.append(['ymyhnhz',61])
    tree.append(['nilfi',10])
    tree.append(['frdln',137, ['ryclt','hxfrni','dyjfhnl']])
    tree.append(['tsrgg',85])
    tree.append(['esnxvu',98])
    tree.append(['mubgcn',42])
    tree.append(['fveygo',57])
    tree.append(['zuhwge',61, ['gyjui','dhanhrw']])
    tree.append(['lmihhgo',27])
    tree.append(['ifyuvj',21])
    tree.append(['ahyhpz',82])
    tree.append(['ziepacp',94])
    tree.append(['nywbm',132])
    tree.append(['cesowu',49])
    tree.append(['ixwrmp',38])
    tree.append(['xknbddc',96])
    tree.append(['ozjskhi',54])
    tree.append(['twrxos',41])
    tree.append(['zjgflu',55])
    tree.append(['sgczxs',79])
    tree.append(['hyrbb',46, ['kqzmkzh','adyard']])
    tree.append(['lqjqj',7708, ['xemsycy','hybiw','fuctso']])
    tree.append(['ghcuf',68])
    tree.append(['fmsede',303, ['iecpcid','aqiyzjv','pcrxyco','htwlpi']])
    tree.append(['lyopa',9])
    tree.append(['qsjas',18])
    tree.append(['ccqfrc',90, ['jtwsltc','wvpurkk']])
    tree.append(['jyuiboq',7])
    tree.append(['lalnt',236, ['fxludfk','osdwa','dlsrkm']])
    tree.append(['jvkuwnl',26])
    tree.append(['zzdnotv',82])
    tree.append(['qqtlw',290, ['ozidy','gigmx']])
    tree.append(['vipxzk',68])
    tree.append(['lhxrely',6])
    tree.append(['lcynwc',8])
    tree.append(['ghkmngk',33])
    tree.append(['bemdu',55])
    tree.append(['kqaeih',38])
    tree.append(['bsdmjnd',55])
    tree.append(['cyrnme',231])
    tree.append(['gosft',69])
    tree.append(['auqkz',68])
    tree.append(['gvuech',88])
    tree.append(['irgxwel',81, ['aiqejps','uqkwa','yxhtf','ghcuf']])
    tree.append(['ygjlqcg',78])
    tree.append(['vqwptq',96])
    tree.append(['dphyg',70, ['bgcudvy','kygfhen','gvgfjab','jhrqcd']])
    tree.append(['rjreuye',76])
    tree.append(['lftee',33, ['illptaw','hzzbk']])
    tree.append(['tvvzyrp',96])
    tree.append(['txvuo',60])
    tree.append(['frrsc',66])
    tree.append(['kmurqns',56])
    tree.append(['hlylkh',88])
    tree.append(['svsfd',142, ['hdrghkp','kdyoc','dulfi']])
    tree.append(['ygcjbtt',97])
    tree.append(['ywzrkz',113, ['olqpfvj','hvdxb']])
    tree.append(['axktcjd',69])
    tree.append(['eqhyjd',77, ['edyopxe','fhirm']])
    tree.append(['nccozmr',90])
    tree.append(['zcmlgn',75203, ['wwtif','spgebj','awkuix']])
    tree.append(['smxutcp',14])
    tree.append(['obsmut',76])
    tree.append(['buoixml',338, ['yramlb','kipfu','nilfi','efaua']])
    tree.append(['ybxios',28])
    tree.append(['rvbxe',120, ['hwcdujm','cdeyze']])
    tree.append(['mreicow',63])
    tree.append(['lzfsc',30])
    tree.append(['bbsbwso',27])
    tree.append(['hosih',206, ['vpfxqm','oocst']])
    tree.append(['nkipd',134, ['tslgtw','tlxbs','pnapirq']])
    tree.append(['seciy',21])
    tree.append(['qvzryn',86])
    tree.append(['jdhzdw',21])
    tree.append(['vesets',45])
    tree.append(['hlseh',51])
    tree.append(['idhvcw',44])
    tree.append(['fdearm',47])
    tree.append(['zuypk',123, ['sxmobi','xknbddc']])
    tree.append(['ttqtuts',19, ['aeumjyu','iykzt','qakvmfc']])
    tree.append(['wpuburp',57])
    tree.append(['bzlaig',98])
    tree.append(['fkchd',164, ['raljfk','povpspa']])
    tree.append(['yhgavb',46])
    tree.append(['krcry',85])
    tree.append(['inzfb',168, ['xxsterg','wozvywq']])
    tree.append(['yhaja',202, ['zuodo','uuzaefz']])
    tree.append(['abbgnrq',96, ['dnlty','rsjst']])
    tree.append(['eqqouz',64])
    tree.append(['nyeqnad',74])
    tree.append(['ahyfxpy',76])
    tree.append(['dtnwui',72])
    tree.append(['hlhvabs',8])
    tree.append(['imciq',110, ['frhsix','wgnjhy']])
    tree.append(['antlr',98])
    tree.append(['dwhpsh',18])
    tree.append(['hypdv',11])
    tree.append(['qnaxzd',5, ['ofmsbwz','veeafpm','rmjchv','umlcaag']])
    tree.append(['zkdvejs',284])
    tree.append(['vuegi',19])
    tree.append(['xkoyskt',68])
    tree.append(['jrkye',88, ['ptdmvq','fcfsd']])
    tree.append(['thvqn',34])
    tree.append(['fwkpb',151, ['ywuie','pcsvt']])
    tree.append(['apmbdgn',98])
    tree.append(['jdfus',94])
    tree.append(['cdvkf',100, ['vbanwb','mnpbbxc','jfgsa']])
    tree.append(['crdqz',26, ['hlhhfys','zldlt']])
    tree.append(['vxbrvx',52, ['kribbus','yuuzzx']])
    tree.append(['rkkuowi',24])
    tree.append(['dlqfl',24])
    tree.append(['ghvxa',76])
    tree.append(['bmrwsem',45])
    tree.append(['kwhcaz',60])
    tree.append(['qcguyb',20])
    tree.append(['fxvjlr',65])
    tree.append(['sdskev',87])
    tree.append(['zvmzo',25])
    tree.append(['sdzdcr',82])
    tree.append(['kipfu',10])
    tree.append(['djshoi',59])
    tree.append(['cfjib',23])
    tree.append(['gytimq',16])
    tree.append(['ithmj',94])
    tree.append(['xgnntny',56])
    tree.append(['tzgilw',208, ['anvlz','kbxmmw']])
    tree.append(['blovei',81])
    tree.append(['bebulic',39])
    tree.append(['dywaqyt',7])
    tree.append(['erjhzv',42])
    tree.append(['cytbrv',25])
    tree.append(['vjnwg',267])
    tree.append(['fzclaow',61, ['hnuck','hmsstu','lqjqj','wlaym','usetp','tpzzyfa','vjkbx']])
    tree.append(['vgyzi',15])
    tree.append(['ewxyrkx',76, ['cnnrve','buoixml','zndohw','qgbbnl','sljqbjl','dezecjo','hhonck']])
    tree.append(['ydilofh',25])
    tree.append(['leblg',53])
    tree.append(['rfqpc',60])
    tree.append(['qmpvl',77])
    tree.append(['dpyamhy',13])
    tree.append(['pjtywfh',99, ['fopaifs','zczzj']])
    tree.append(['hmocs',44])
    tree.append(['mracmcq',28])
    tree.append(['hpqjl',69])
    tree.append(['acxsu',35])
    tree.append(['gyhnr',92])
    tree.append(['ppqjh',89])
    tree.append(['ofmsbwz',247, ['yzglw','foqcvf']])
    tree.append(['nyeck',696, ['fjtqmt','tpgwqt','kzqki']])
    tree.append(['kcqkcz',62])
    tree.append(['ofhps',38])
    tree.append(['vfjnsd',4402, ['quempkz','xvlxy','tulwp']])
    tree.append(['itjoisx',14])
    tree.append(['ogomr',198, ['wlnvlvv','wccui']])
    tree.append(['sovii',90])
    tree.append(['vmypqee',165, ['dtdrq','rjich']])
    tree.append(['ppmjtea',58, ['dnnzhd','lecjqrc','zvofir','ajytayr']])
    tree.append(['swtjb',10])
    tree.append(['jxlak',16])
    tree.append(['ybvbei',21])
    tree.append(['lyilhws',89])
    tree.append(['aufrup',42])
    tree.append(['xiollwu',24])
    tree.append(['jomewfa',79])
    tree.append(['yhchshd',286, ['sjvozur','sysqfo']])
    tree.append(['lheawf',77])
    tree.append(['hmsstu',91, ['xgpkw','oebbzys','vmfodw','ewxyrkx','qaspfj','jpeea']])
    tree.append(['nxkawc',9])
    tree.append(['tilip',789, ['hewqufa','crstch','taron']])
    tree.append(['zajkvp',90])
    tree.append(['nyyqkh',217, ['lbkxp','ubxusjq']])
    tree.append(['swdcc',293, ['lzfsc','tgeefln']])
    tree.append(['xjbkl',11, ['isxnnce','wufzoga','wxtzk']])
    tree.append(['kvdvsr',137])
    tree.append(['qucgz',87])
    tree.append(['cfneir',69])
    tree.append(['zbodcwy',99, ['qwthf','acufa','mqwnw','qrtvd']])
    tree.append(['flxmb',16])
    tree.append(['vwmgmf',46, ['iwmeu','qrrfj','byfcat']])
    tree.append(['nuwcul',46, ['dhdeayl','bbccojb','qkfeemt','bjifxso']])
    tree.append(['gwvwgyr',5])
    tree.append(['kdrfg',85])
    tree.append(['sdcdu',9])
    tree.append(['tllopby',96])
    tree.append(['ghyax',30])
    tree.append(['newnawd',256, ['jmeken','hjcphe']])
    tree.append(['ggqro',146, ['blwjcp','ynleow']])
    tree.append(['fhbbe',47, ['tdqaege','phkek']])
    tree.append(['kzbfyep',98])
    tree.append(['zvskx',111, ['rfqpc','kmfvh']])
    tree.append(['wnmje',35])
    tree.append(['dwpmy',133, ['pcduo','cexino']])
    tree.append(['aeumjyu',97])
    tree.append(['jjkrqj',6])
    tree.append(['gkmkjyr',66])
    tree.append(['ivobx',45])
    tree.append(['ytnhd',112, ['jdhzdw','pyvum','qxiutp','yjcytj']])
    tree.append(['tzylg',69])
    tree.append(['khlwul',48])
    tree.append(['cycimm',37])
    tree.append(['vowidrd',45])
    tree.append(['rxvyryq',63])
    tree.append(['postmlp',4609, ['bkesn','ljfdk','uugdix','txvil']])
    tree.append(['ianvxjm',95])
    tree.append(['rpbmn',57, ['igbewg','blovei']])
    tree.append(['iuthq',99])
    tree.append(['azegzz',63])
    tree.append(['pwvvaw',245])
    tree.append(['uehaezr',189, ['lzrcpf','dyjywtj']])
    tree.append(['pvcbg',85])
    tree.append(['sdehr',7])
    tree.append(['ikntvuy',79])
    tree.append(['hgwrue',39])
    tree.append(['heioj',51])
    tree.append(['lrrdrb',94])
    tree.append(['wqiene',79, ['thtpl','juoxs','bivbw','pfiwzws']])
    tree.append(['jfgsa',55])
    tree.append(['xmvipsu',69])
    tree.append(['yimofqp',50])
    tree.append(['pvwsgxh',9001, ['vtpiz','dzaxux','trvqvb','tswygt']])
    tree.append(['secjdhk',29, ['fyzkj','zayadh']])
    tree.append(['jiufw',41])
    tree.append(['sompy',19])
    tree.append(['kvgtcm',112])
    tree.append(['jcfix',55, ['onjgrby','tseejl','pbmrflr','jhnoba','fuxuvbn','nnfwd']])
    tree.append(['bajeppo',21])
    tree.append(['uqkwa',68])
    tree.append(['iwmuonh',296, ['omowchx','qnzwa']])
    tree.append(['dyyzr',80])
    tree.append(['klaqwj',67, ['qmpvl','cwexwaz']])
    tree.append(['jjeyyc',40, ['gblchqc','hpygxqx']])
    tree.append(['gzpma',111, ['amuyprv','dorcc']])
    tree.append(['vlajq',157, ['aosedtz','vescu']])
    tree.append(['mjfsqls',63])
    tree.append(['nqhah',42])
    tree.append(['xrktj',90])
    tree.append(['wscmp',42, ['eyyypjs','opxtj']])
    tree.append(['ivotjym',72])
    tree.append(['dwzeri',122, ['vkpdskd','sdehr']])
    tree.append(['zgqnd',36])
    tree.append(['zqparby',962, ['hkauzoo','phtiu','qtgmnht']])
    tree.append(['dnlty',85])
    tree.append(['fffuhf',647, ['jjeyyc','ccjrwmk','jrilj','jgysg','pmmzezq']])
    tree.append(['bvurv',227, ['muczne','yrobppu']])
    tree.append(['oxzwlk',90])
    tree.append(['gyjyiu',47])
    tree.append(['ewlkda',68, ['ivotjym','qhqhx']])
    tree.append(['cxbcib',219])
    tree.append(['yprbzn',25])
    tree.append(['qijkhbz',94])
    tree.append(['runxvuj',58])
    tree.append(['tybkxd',32])
    tree.append(['iyqsn',11])
    tree.append(['vszgnbj',402])
    tree.append(['ichekvx',2035, ['yfccf','mhuwxy','rvbxe']])
    tree.append(['xqnwm',90, ['rjreuye','weqoyg']])
    tree.append(['btpwtub',31])
    tree.append(['mcqbzy',60])
    tree.append(['bbgkrav',43])
    tree.append(['inrkd',57])
    tree.append(['wuxqatm',67])
    tree.append(['pkmsa',48])
    tree.append(['ktlgsn',585, ['kpdnx','nlonnkx','ujryrca']])
    tree.append(['dxclu',45])
    tree.append(['trjqu',63])
    tree.append(['mfoinlm',94])
    tree.append(['xkhavpc',91])
    tree.append(['qwthf',64])
    tree.append(['gpesq',244, ['spznevr','cuaou']])
    tree.append(['geuog',46])
    tree.append(['onqfc',14, ['kqfwwv','gfagn','woujjmo','tkcqnb']])
    tree.append(['tlxmg',60])
    tree.append(['tjngq',55])
    tree.append(['wccui',14])
    tree.append(['zxdcbk',42])
    tree.append(['sbuzab',28])
    tree.append(['ppiyhx',25])
    tree.append(['frxenhe',91])
    tree.append(['zpghac',32])
    tree.append(['gdjplif',60, ['dautk','azbhibc']])
    tree.append(['ncrtwlq',94])
    tree.append(['avlbm',85, ['neixysk','clpia']])
    tree.append(['mxjxqd',24])
    tree.append(['bqlsax',77])
    tree.append(['afqujq',219])
    tree.append(['fipbn',15])
    tree.append(['bmjxtay',85])
    tree.append(['emcour',54, ['nhobovg','wcfykrj','wuxqatm','hcnzejq']])
    tree.append(['cifgld',124, ['rveuds','dqpng','thvqn']])
    tree.append(['qaktp',72])
    tree.append(['mzfnhhp',208, ['uefgi','ydilofh']])
    tree.append(['cnnrve',186, ['yufzzgy','tvvzyrp']])
    tree.append(['tdjqll',95, ['khmkmb','qnjlq','znqtjeb']])
    tree.append(['vbcwp',31])
    tree.append(['qrybtpr',49])
    tree.append(['vjkbx',7351, ['nidfyzu','mtzdbty','pszgrn','xkmzwq']])
    tree.append(['xjqhzdl',194, ['zcruqaw','cycimm']])
    tree.append(['eewro',5])
    tree.append(['jcyvs',189, ['oupnrtc','ifyuvj']])
    tree.append(['cumfazk',41])
    tree.append(['gkgbww',235, ['epvrmk','bajeppo']])
    tree.append(['hzdjjg',79])
    tree.append(['jpfnrj',24])
    tree.append(['juoxs',93])
    tree.append(['kfahk',302, ['gkmkjyr','mxibrwp']])
    tree.append(['vaxyae',216, ['ssebu','vjiprx']])
    tree.append(['ubsxskk',323])
    tree.append(['pszgrn',672, ['kclwabx','fkchd','nxnvm','hdevhyk','jkoeof','tcyvkaf','ajnkrwf']])
    tree.append(['btfdruj',87])
    tree.append(['higxu',88])
    tree.append(['rtiwxq',154, ['gpxam','yauum','dszjuo','tfwgxrq']])
    tree.append(['ptdmvq',95])
    tree.append(['nudeuz',406, ['cwrmfzk','jqtws']])
    tree.append(['clxelo',60])
    tree.append(['gwbssq',27])
    tree.append(['kfcucr',82])
    tree.append(['zayadh',83])
    tree.append(['fklkx',191, ['xuxxxmh','tibjuc']])
    tree.append(['llqdavt',61])
    tree.append(['abrvrcv',44])
    tree.append(['vxnrpq',94, ['hkxsh','jomewfa']])
    tree.append(['pnxeoq',69, ['sbuzab','ylunw']])
    tree.append(['yzglw',53])
    tree.append(['ymetywq',35])
    tree.append(['khmkmb',85])
    tree.append(['nfxyklo',10174, ['btoap','gfhpte','lalnt']])
    tree.append(['kzqki',227])
    tree.append(['hyqxc',33])
    tree.append(['rvntovh',87])
    tree.append(['isxnnce',81])
    tree.append(['krunds',173])
    tree.append(['iwmeu',58])
    tree.append(['oxtumtn',87])
    tree.append(['hppnn',232, ['pjymo','qsjas']])
    tree.append(['drtzf',9])
    tree.append(['jgcfh',269, ['ffbhje','ewfigm']])
    tree.append(['qwhzogh',65])
    tree.append(['hxzlw',11])
    tree.append(['aepgud',54, ['mkqze','qryoc']])
    tree.append(['zegoehg',93])
    tree.append(['qxvnf',724, ['uchwojr','jxknrj','kasjbl','hyzcrj','secjdhk','vikokw']])
    tree.append(['osovcq',72])
    tree.append(['dxddyhh',5])
    tree.append(['vrbhapd',80, ['zgvhx','lytxt']])
    tree.append(['rrymbf',231])
    tree.append(['ebchb',84])
    tree.append(['irqxygl',1812, ['agmtzo','jwhcs']])
    tree.append(['vchbwy',95])
    tree.append(['svyuvhk',137, ['iapwe','evvgx']])
    tree.append(['hnpbcb',88])
    tree.append(['swotlas',869, ['vlajq','rkyrvy','ddqvjcz']])
    tree.append(['aptjv',142, ['preebof','xgnntny']])
    tree.append(['lbzwb',197, ['zprutpl','wjbbg']])
    tree.append(['seack',32])
    tree.append(['uzybpoz',68])
    tree.append(['gxgrdez',31])
    tree.append(['dngxvvl',60])
    tree.append(['vuxruoi',226, ['gqdxofo','nfbyk']])
    tree.append(['lcidw',97, ['xbipb','wndcqx','ryluuhv']])
    tree.append(['kfrwimb',53])
    tree.append(['vkubjgp',80])
    tree.append(['zldlt',84])
    tree.append(['gpxam',256, ['krythkn','pnmirw']])
    tree.append(['pzjusto',40])
    tree.append(['neixysk',68])
    tree.append(['gyftdi',78])
    tree.append(['uciitam',247, ['mfmnp','uzybpoz']])
    tree.append(['zijpzl',55])
    tree.append(['ddkvjl',23])
    tree.append(['qekqaz',35])
    tree.append(['vkwfac',51])
    tree.append(['ndnhrj',45])
    tree.append(['vqenunc',56, ['hisqsfr','hyagspc']])
    tree.append(['txvil',2316, ['vwzwnip','wxtvn','kvgtcm']])
    tree.append(['apkxv',6])
    tree.append(['mjkcz',65])
    tree.append(['uwklen',64])
    tree.append(['nmxpqnh',59])
    tree.append(['piqus',65])
    tree.append(['jxuncn',73])
    tree.append(['ffbhje',42])
    tree.append(['bptud',35])
    tree.append(['ezghsl',97])
    tree.append(['qhblzff',14830, ['rvtwdl','jgmxdc','zjwxdsl']])
    tree.append(['lunozxs',48])
    tree.append(['jwdlpw',10])
    tree.append(['lgzam',78])
    tree.append(['tdwgne',68])
    tree.append(['xjcil',88])
    tree.append(['vlzaeq',102, ['kqaeih','ofhps']])
    tree.append(['dyjfhnl',12])
    tree.append(['wufzoga',81])
    tree.append(['cqurt',119, ['sdigrgk','qsdfdw','inrkd']])
    tree.append(['xemsycy',973, ['szkcigt','navfz','mtpqiok','bilbbf','ecviwn','emcour']])
    tree.append(['xklheqv',44])
    tree.append(['nfbyk',14])
    tree.append(['nehjwq',45])
    tree.append(['ejggu',155, ['cqgumz','nxdselb']])
    tree.append(['bltzxtt',41])
    tree.append(['fudyri',24])
    tree.append(['bwuyaa',24])
    tree.append(['pbinkz',58])
    tree.append(['psfmvag',60])
    tree.append(['xaycoki',82])
    tree.append(['kcdvc',1299, ['kxsxtd','nmxpqnh']])
    tree.append(['dulfi',42])
    tree.append(['uczsgkq',64])
    tree.append(['jxdpg',14])
    tree.append(['jroccc',82])
    tree.append(['pjymo',18])
    tree.append(['bgnlm',98])
    tree.append(['oasfpl',59])
    tree.append(['fhlzh',72])
    tree.append(['ntiulub',6])
    tree.append(['gynyaeu',15])
    tree.append(['trukr',5539, ['rssegj','csfac','ymobi','iljmpy']])
    tree.append(['ldxjzcc',69, ['bgnlm','bzlaig']])
    tree.append(['otxfx',65])
    tree.append(['gttojem',50])
    tree.append(['tarlgrd',65])
    tree.append(['mqiyn',66])
    tree.append(['kygfhen',83])
    tree.append(['dutiad',403, ['yugdmgx','cytbrv']])
    tree.append(['dcwngp',13])
    tree.append(['ijzvrcj',8])
    tree.append(['hgbhi',90])
    tree.append(['lrewm',10])
    tree.append(['ktvub',44])
    tree.append(['ozidy',12])
    tree.append(['fyzkj',83])
    tree.append(['ufjnfv',18])
    tree.append(['okcbif',35])
    tree.append(['aqkshy',74])
    tree.append(['blfqvmp',41, ['wbyfgrk','zzgtrsz','gunqzbu','xydbtk','mybfzn','tpfcenm']])
    tree.append(['wstoc',71])
    tree.append(['mqlgugi',21])
    tree.append(['wqussp',59])
    tree.append(['kpcwye',7])
    tree.append(['pimwe',404])
    tree.append(['gxvbg',67])
    tree.append(['lnpdxkz',19, ['kfahk','myuqc','puhghe','ocboj','nqhyusz','unegqpm']])
    tree.append(['zuodo',29])
    tree.append(['dqtranb',21])
    tree.append(['rveiwr',23])
    tree.append(['wdbub',57])
    tree.append(['vcjjb',75])
    tree.append(['ihbwov',95])
    tree.append(['ipmtfwk',47])
    tree.append(['khzoaxo',56])
    tree.append(['axwrsy',80])
    tree.append(['axees',82])
    tree.append(['nznkw',24])
    tree.append(['ibkwb',13, ['rskvj','tnncdvi','vxwudy','euukxkh']])
    tree.append(['qazahe',95])
    tree.append(['pivhdjq',15])
    tree.append(['cfbxssz',53])
    tree.append(['swscx',31])
    tree.append(['uggosj',51])
    tree.append(['fuxuvbn',396, ['lcynwc','mmjuj']])
    tree.append(['gphzut',38, ['epxnk','dxogq','vtryv','ibphxp','qabjz','kiocz']])
    tree.append(['hmlcfic',1148, ['qerpj','yorumsq','mtoet','qiwpw','afqujq']])
    tree.append(['wwtif',15, ['irqxygl','xsgud','qxvnf','riimx','kbpdvgx','hmuvntc','opbvo']])
    tree.append(['yramlb',10])
    tree.append(['kdzri',313])
    tree.append(['cnblm',60])
    tree.append(['uicqk',76])
    tree.append(['kjmxrt',42])
    tree.append(['jauss',95])
    tree.append(['vazzmfm',155, ['vuegi','ztoof','sompy','wltqbe']])
    tree.append(['laxzy',66])
    tree.append(['eklij',89])
    tree.append(['pnapirq',13])
    tree.append(['nidfyzu',1617, ['iodeix','fvyqhob','qyywjjj']])
    tree.append(['aejjn',152, ['jnhjfg','xtpqgw']])
    tree.append(['jrilj',142, ['kewvll','khaofpf']])
    tree.append(['euukxkh',85])
    tree.append(['etxasz',459, ['kihgxqn','phjdo','kmvyfai','ghsmpke','nqtrrnh']])
    tree.append(['dugvl',74])
    tree.append(['lsbzyx',226])
    tree.append(['czrjoz',27])
    tree.append(['ydgsome',91, ['clpswz','mqiyn','fzadipq','qkwni']])
    tree.append(['dlolw',77])
    tree.append(['qsdfdw',57])
    tree.append(['geygl',63])
    tree.append(['hcjslif',30])
    tree.append(['mfbagfq',94])
    tree.append(['wbqsg',47])
    tree.append(['tpgwqt',37, ['ulwtqfp','wupujt']])
    tree.append(['qquge',212])
    tree.append(['ppfgq',71, ['fdnlfw','nehjwq']])
    tree.append(['ivgdluw',48])
    tree.append(['ghsmpke',175, ['bioprb','ewtsnjb']])
    tree.append(['noftq',29])
    tree.append(['rcgbe',322, ['tzpoh','txyftk']])
    tree.append(['oyabiot',41])
    tree.append(['fhtkd',65])
    tree.append(['owqobwu',142, ['xnbut','qsprrb']])
    tree.append(['bqbsz',209, ['ezrvccj','neiawsy']])
    tree.append(['clhgsb',11])
    tree.append(['fggqv',90])
    tree.append(['wozvywq',87])
    tree.append(['blwjcp',72])
    tree.append(['wmpeyz',25])
    tree.append(['mtzdbty',1200, ['rtvetjy','mmfkf','vlzaeq','imciq','rvlna','ymmoez']])
    tree.append(['jmeken',27])
    tree.append(['qxiutp',21])
    tree.append(['bcsmd',250, ['jgmxxac','atdbx']])
    tree.append(['yufzzgy',96])
    tree.append(['sudojso',34, ['pqbatbl','fmsede','ijqfwj','jhwxxmc','uciitam']])
    tree.append(['dnzxj',13016, ['nyeck','tilip','djdztah']])
    tree.append(['jwhcs',41])
    tree.append(['lwjexjg',75])
    tree.append(['uivra',37])
    tree.append(['cjexce',89])
    tree.append(['xnbut',50])
    tree.append(['ytfqdj',31])
    tree.append(['kxezytz',163, ['jiufw','oyabiot']])
    tree.append(['hhxwcq',20])
    tree.append(['vmfodw',1946, ['mzgecu','wjswjjk','crdqz','twwimz']])
    tree.append(['mdvfsjt',65])
    tree.append(['lncvfka',35])
    tree.append(['anvlz',13])
    tree.append(['iprdoum',30])
    tree.append(['trvqvb',134, ['zkdvejs','bcsmd','htbso','scmer','tnutmxv']])
    tree.append(['icwxs',75])
    tree.append(['bwszv',347, ['pmmwcg','jowbm']])
    tree.append(['hrjkg',77])
    tree.append(['aiqejps',68])
    tree.append(['nzokis',33])
    tree.append(['tpfcenm',240, ['jxuncn','bhvpcqs']])
    tree.append(['vdbds',51])
    tree.append(['djvzshb',98, ['xgmcuzc','xauvth','antlr']])
    tree.append(['kqzmkzh',54])
    tree.append(['msdkszz',51])
    tree.append(['yedeqj',1867, ['wuqyrfk','beocgcy','gzpma','eqhyjd']])
    tree.append(['uibkcpe',11])
    tree.append(['zfzybq',55, ['pdfnqi','dlolw','pdiie','lheawf']])
    tree.append(['tbmyzr',30])
    tree.append(['zqljt',55])
    tree.append(['heradq',132, ['dtnwui','fhlzh']])
    tree.append(['txyftk',38])
    tree.append(['komast',245])
    tree.append(['wufaj',174, ['kjmxrt','nqhah']])
    tree.append(['woizpm',82, ['axwrsy','dyyzr']])
    tree.append(['hphlcxp',97, ['rtlcg','vrxhty']])
    tree.append(['afjclgu',27])
    tree.append(['qrxvqe',238, ['gxgrdez','xhwkcn']])
    tree.append(['gblchqc',57])
    tree.append(['qnqir',50])
    tree.append(['preebof',56])
    tree.append(['zwysutd',23, ['cfneir','mssvilz']])
    tree.append(['rjohk',6])
    tree.append(['mcqabbl',51, ['aizvg','ivobx','gbvowdh','tyxuz']])
    tree.append(['iqxqmc',92])
    tree.append(['hazyvie',132, ['ekcrfnr','excsvdc']])
    tree.append(['qaspfj',1106, ['gmlbsa','gpesq','dtvjbm','pimwe']])
    tree.append(['dmdxjmt',51])
    tree.append(['mzxret',28])
    tree.append(['fbnge',52])
    tree.append(['xgmcuzc',98])
    tree.append(['yauum',46, ['llzboz','lzrav','mwofrtn','kflwup']])
    tree.append(['dezecjo',230, ['ccikbql','otxilwl']])
    tree.append(['jqtws',29])
    tree.append(['wauprfk',131, ['laxzy','ewflis']])
    tree.append(['iikdtt',184, ['jnlnp','praqutu']])
    tree.append(['qxnuybx',48])
    tree.append(['yuhoog',38, ['vbnbtrd','lmdzx','jborbj']])
    tree.append(['zvledr',129, ['jacnhvn','flxmb']])
    tree.append(['pngigbs',20])
    tree.append(['vqpkcu',860, ['ndiyxee','lhgstq','zfzybq']])
    tree.append(['zfjcea',308, ['gyjyiu','vfrbqk']])
    tree.append(['ansxn',85])
    tree.append(['kekcm',836, ['ulurun','fmijcj','kwhcaz','cnblm']])
    tree.append(['vxqdrzk',33])
    tree.append(['sinsn',13, ['mjkcz','bwomuu','iyjjp']])
    tree.append(['wnlma',51])
    tree.append(['excsvdc',59])
    tree.append(['yyimzla',94])
    tree.append(['zhjvk',60])
    tree.append(['hwcdujm',7])
    tree.append(['usetp',5755, ['zqztqd','ktlgsn','ncgmykk','gjowlue','wjbpo','vuskd','abqsqsw']])
    tree.append(['lbkxp',48])
    tree.append(['hcnzejq',67])
    tree.append(['yuuzzx',91])
    tree.append(['orecwx',142, ['pvbqjz','dxclu','puozu']])
    tree.append(['dnpap',51])
    tree.append(['jvtkvxk',281, ['fdearm','lymfce']])
    tree.append(['rgqohx',45])
    tree.append(['orrks',84])
    tree.append(['ziuhn',95])
    tree.append(['fdnlfw',45])
    tree.append(['qkwni',66])
    tree.append(['hewqufa',196])
    tree.append(['acufa',64])
    tree.append(['ijqfwj',247, ['auqkz','cnmxf']])
    tree.append(['qewogca',49])
    tree.append(['bhvpcqs',73])
    tree.append(['lugeqg',2180, ['oxhuvih','yaucaw','sguuvok']])
    tree.append(['mnpbbxc',55])
    tree.append(['kdyoc',42])
    tree.append(['epbewj',58])
    tree.append(['vxzlg',69, ['phawl','xjqlt','iyqvz']])
    tree.append(['lntlxre',71])
    tree.append(['ujryrca',76, ['sgczxs','ikntvuy','micap']])
    tree.append(['hdrghkp',42])
    tree.append(['qfpunan',189, ['bbelj','nrvdexu']])
    tree.append(['hkxsh',79])
    tree.append(['wfwor',45])
    tree.append(['ivbzfo',10])
    tree.append(['veowdxy',133, ['zkzcu','zqljt','pqwtmk']])
    tree.append(['spriicr',63])
    tree.append(['rraaooy',1643, ['jlnxmnt','klaqwj','avlbm','njusfd']])
    tree.append(['rrcgjc',16])
    tree.append(['lzsnst',222, ['zqfkx','zikfenq']])
    tree.append(['bgelipj',33])
    tree.append(['quempkz',1225, ['ndait','vpkkrb','hphlcxp']])
    tree.append(['mljbkl',10, ['shryh','glyfb','cqlwmo','ixiugzp']])
    tree.append(['ljihyoy',85])
    tree.append(['vqdbb',60])
    tree.append(['htbso',96, ['jdfus','bxpmf']])
    tree.append(['cdeyze',7])
    tree.append(['dsknoh',4511, ['btrafox','dhsku','sjzvkno','hmlcfic','evemn','ainak','kmpxcdm']])
    tree.append(['iyqvz',82])
    tree.append(['jpeea',2545, ['mxbsj','izhrthy','oasfpl']])
    tree.append(['hvdxb',75])
    tree.append(['bivbw',93])
    tree.append(['uhteq',12])
    tree.append(['ndait',181, ['qfkpanu','wlgsuj']])
    tree.append(['yjcytj',21])
    tree.append(['fmzdg',55])
    tree.append(['zwwlue',47])
    tree.append(['xsgud',904, ['ppmjtea','spyosq','ozdamth']])
    tree.append(['ryclt',12])
    tree.append(['azbhibc',89])
    tree.append(['mzmwtg',110, ['bbgkrav','yzcgrkk']])
    tree.append(['bfhgdou',155, ['ndnhrj','gwowni']])
    tree.append(['blsyfi',94])
    tree.append(['nwptea',96])
    tree.append(['exwagrs',25])
    tree.append(['nngqjua',15])
    tree.append(['zwrhhqv',91])
    tree.append(['wqgfmh',57])
    tree.append(['opxtj',86])
    tree.append(['gohsqql',51])
    tree.append(['hxfrni',12])
    tree.append(['hbtzel',88])
    tree.append(['eylhve',8, ['mwmpp','joduj','ygsse','gyhnr']])
    tree.append(['sdigrgk',57])
    tree.append(['ltnxno',118, ['kxphfg','phkrmkb']])
    tree.append(['aewpztq',36])
    tree.append(['clpia',68])
    tree.append(['spyjrzi',355, ['dqnif','tfjeo']])
    tree.append(['ixiugzp',98])
    tree.append(['fanqwrt',44, ['bdbaph','wpbwt']])
    tree.append(['igbewg',81])
    tree.append(['ujruya',89])
    tree.append(['iykzt',97])
    tree.append(['sujgkaw',40])
    tree.append(['ypmviuh',60, ['dxmqgds','veowdxy','ywnbh','zokot','bfwovd']])
    tree.append(['ybjde',40])
    tree.append(['nemqds',77, ['uesje','khyng']])
    tree.append(['onqtz',68])
    tree.append(['qyywjjj',75, ['rqqcyu','lntlxre']])
    tree.append(['ranrjjb',69])
    tree.append(['taron',86, ['xsehs','nbxyhp']])
    tree.append(['kxudhlx',66, ['eqqouz','uwklen','uopfe']])
    tree.append(['ykbmqm',28])
    tree.append(['dtjjjie',91])
    tree.append(['wupujt',95])
    tree.append(['plptt',179, ['rvntovh','dzvnjwy']])
    tree.append(['djwzsa',34])
    tree.append(['zjtchm',227, ['npkafp','ffjip','ayyaq']])
    tree.append(['frebmn',65, ['iqycdt','vkftq','ginbdt']])
    tree.append(['phjdo',105, ['qwhzogh','plkvbhb']])
    tree.append(['zvhpm',5])
    tree.append(['suyuh',44])
    tree.append(['xehzoaw',16])
    tree.append(['scppxlw',93])
    tree.append(['npkafp',71])
    tree.append(['vtryv',210, ['fkdnk','dlqfl']])
    tree.append(['jxknrj',195])
    tree.append(['agmtzo',41])
    tree.append(['pdfnqi',77])
    tree.append(['kpxbfji',14])
    tree.append(['pybcu',267, ['abrvrcv','kgarj']])
    tree.append(['zzgtrsz',326, ['laktqu','hcjslif']])
    tree.append(['qakvmfc',97])
    tree.append(['xqcvk',23])
    tree.append(['kppjorc',105, ['heioj','jdoysh','vdbds']])
    tree.append(['epxnk',98, ['fksbg','zksrdel']])
    tree.append(['lldbah',14, ['kzdewu','qazahe']])
    tree.append(['amuyprv',39])
    tree.append(['ynaeh',11])
    tree.append(['mrkxs',67])
    tree.append(['xhwkcn',31])
    tree.append(['ehzqs',5])
    tree.append(['rhtltex',85, ['bdfblio','ypahi']])
    tree.append(['cuaou',80])
    tree.append(['bjifxso',88])
    tree.append(['fmijcj',60])
    tree.append(['xtbfzkp',250, ['axhcob','pvrff']])
    tree.append(['pybtxv',65])
    tree.append(['bioprb',30])
    tree.append(['nqhyusz',336, ['kjgwca','ixkdgf']])
    tree.append(['efaua',10])
    tree.append(['mfzhe',8])
    tree.append(['isdwz',43, ['hmfozm','zfeudr','inzfb','pvtbmzi','gzuvfqc','aahwvmb','wxakfgm']])
    tree.append(['tqpoo',65])
    tree.append(['pqwtmk',55])
    tree.append(['uxwov',27])
    tree.append(['qnzwa',7])
    tree.append(['sbwadli',15])
    tree.append(['cexino',49])
    tree.append(['liqfvgz',47])
    tree.append(['yqywtzl',55])
    tree.append(['mnetsv',260, ['zwwlue','wbqsg']])
    tree.append(['ymmoez',106, ['ycjdb','aewpztq']])
    tree.append(['hmuvntc',1165, ['xanuprn','hyyczqe','oniakw']])
    tree.append(['gqjmp',221])
    tree.append(['yvhgo',80])
    tree.append(['fzadipq',66])
    tree.append(['ewtsnjb',30])
    tree.append(['qhinsi',24, ['ziepacp','yyimzla']])
    tree.append(['hvlpcew',45])
    tree.append(['xydbtk',386])
    tree.append(['dzvnjwy',87])
    tree.append(['jkoeof',68, ['lifhy','svlhbcy']])
    tree.append(['tjcmctp',258, ['ehzqs','psmylp']])
    tree.append(['myecan',402])
    tree.append(['fwxdhe',13])
    tree.append(['hxnxq',9])
    tree.append(['laktqu',30])
    tree.append(['vkftq',83])
    tree.append(['mchmeiz',303, ['dfqzdr','nngnivo']])
    tree.append(['uaeeza',80])
    tree.append(['wtgjv',62])
    tree.append(['nguoj',98])
    tree.append(['fltcx',13])
    tree.append(['xuxkwp',36])
    tree.append(['liprz',837, ['uogjfe','jrkye','wcswjri','ffqjbfe']])
    tree.append(['bnkcs',172, ['uxwov','cdhfwg']])
    tree.append(['aahwvmb',226, ['auhjkqg','pgxppw']])
    tree.append(['kclwabx',94, ['zucwwm','eolje']])
    tree.append(['ksxpomr',18, ['qbnzq','otity']])
    tree.append(['vkpdskd',7])
    tree.append(['gvamy',66])
    tree.append(['khdjiyr',31])
    tree.append(['jcrly',81, ['kqrpmtu','bxyfc','hzdjjg','evapx']])
    tree.append(['sqybc',81, ['gotjxc','yedhrqg','ppmiyqf','mudpzad']])
    tree.append(['rvlna',73, ['wdrjftp','frmsjzw','wnmje']])
    tree.append(['wlgsuj',49])
    tree.append(['yzcgrkk',43])
    tree.append(['mssvilz',69])
    tree.append(['jhnoba',380, ['xehzoaw','lxuwkr']])
    tree.append(['gzzodai',84])
    tree.append(['gbxvor',64])
    tree.append(['otxum',67])
    tree.append(['tacjmyy',43])
    tree.append(['hmfozm',266, ['hwwea','ooike']])
    tree.append(['mudpzad',41])
    tree.append(['zkkwvo',140, ['kpcwye','tefvwb']])
    tree.append(['bcylzy',35])
    tree.append(['uefgi',25])
    tree.append(['jgmxxac',17])
    tree.append(['mnqvu',60])
    tree.append(['wxtzk',81])
    tree.append(['sljqbjl',240, ['hpqjl','tzylg']])
    tree.append(['ujudwk',270, ['qvujwr','nrrops']])
    tree.append(['uugdix',1614, ['fwsxuc','frdln','nkipd','gvytaes','fyudu','krunds']])
    tree.append(['lifhy',80])
    tree.append(['ibphxp',150, ['agczxc','ylxvd']])
    tree.append(['yjlat',41])
    tree.append(['ffjip',71])
    tree.append(['puozu',45])
    tree.append(['jtwsltc',24])
    tree.append(['ctvjzip',45])
    tree.append(['wvstx',178, ['uhteq','rzeyzb','ajxbw']])
    tree.append(['ujaxyn',54])
    tree.append(['vtpiz',426, ['evrgojz','eylhve','yhchshd']])
    tree.append(['osdwa',85, ['yvhgo','ulgox']])
    tree.append(['wpbwt',82])
    tree.append(['xjqlt',82])
    tree.append(['bedla',98])
    tree.append(['xakrpew',72])
    tree.append(['upsrogz',21])
    tree.append(['zqijwcd',55])
    tree.append(['dzaxux',84, ['bvurv','pwvvaw','sqybc','rgnnme','gxjbow','komast']])
    tree.append(['tuvdk',192, ['zxuigx','iyqsn','carik']])
    tree.append(['omowchx',7])
    tree.append(['bmpdcge',17])
    tree.append(['aknsq',161, ['djwzsa','ihciz','gmvxx']])
    tree.append(['rsjst',85])
    tree.append(['weqoyg',76])
    tree.append(['mybfzn',234, ['elndeja','vbnyv']])
    tree.append(['dppmh',67])
    tree.append(['zdrfpo',30])
    tree.append(['wqvjpwa',88])
    tree.append(['vjiprx',47])
    tree.append(['ghfcln',62])
    tree.append(['lzfgxlb',46434, ['ipnia','qmjdqb','dnzxj','ddotjil']])
    tree.append(['xewab',20])
    tree.append(['ceypzh',63])
    tree.append(['ammlo',98])
    tree.append(['gorrq',299, ['ybxios','kaezunt']])
    tree.append(['hwwea',38])
    tree.append(['ocxox',60])
    tree.append(['dlsrkm',245])
    tree.append(['inswkfm',105, ['hrqdm','osovcq']])
    tree.append(['awkuix',12629, ['zwysutd','ppfgq','ftbil','zvledr']])
    tree.append(['tseejl',56, ['pdzqzk','eklij','ppqjh','sbkfcbh']])
    tree.append(['zdtwo',6])
    tree.append(['kmfvh',60])
    tree.append(['alhox',33])
    tree.append(['fvyqhob',67, ['lwjexjg','niexrb']])
    tree.append(['qhrye',287, ['fwxdhe','dcwngp']])
    tree.append(['ddzbs',28])
    tree.append(['texmxw',99])
    tree.append(['phkrmkb',70])
    tree.append(['hwtudr',35])
    tree.append(['yaucaw',37, ['vntnpm','mopjtoj']])
    tree.append(['aizvg',45])
    tree.append(['dxbjv',69, ['ahyfxpy','uifttbe']])
    tree.append(['pdbejtw',80])
    tree.append(['epufxrr',50])
    tree.append(['spyosq',300, ['wnvqy','fjxoyo']])
    tree.append(['ghnbgge',82])
    tree.append(['fwmowjn',338, ['ynaeh','hxzlw']])
    tree.append(['oxvjudn',76, ['frxenhe','wxrqjvy']])
    tree.append(['xtpqgw',81])
    tree.append(['clskgfl',19])
    tree.append(['dnnzhd',68])
    tree.append(['eecmcs',229, ['mreicow','mjfsqls']])
    tree.append(['oameej',25])
    tree.append(['yslnjr',82])
    tree.append(['emxlqwq',18, ['wqussp','trunx']])
    tree.append(['ritcku',120, ['liqfvgz','dkzjztp']])
    tree.append(['mwofrtn',78])
    tree.append(['gmvxx',34])
    tree.append(['foqcvf',53])
    tree.append(['wbyfgrk',320, ['vxqdrzk','alhox']])
    tree.append(['phtiu',84, ['ubiyjs','zicqv','ymetywq','zvrvvky']])
    tree.append(['burxc',42])
    tree.append(['hnhcg',10])
    tree.append(['icqjwqy',162, ['ddkvjl','muwgzs']])
    tree.append(['zucwwm',67])
    tree.append(['ijfjve',72])
    tree.append(['fvpns',45])
    tree.append(['ocboj',266, ['csrpgne','zzsbho']])
    tree.append(['cithkzk',88])
    tree.append(['vioxr',69])
    tree.append(['myqrqql',2330, ['sdcdu','hxnxq','nxkawc']])
    tree.append(['axhcob',74])
    tree.append(['pgebb',315])
    tree.append(['vzamfb',89])
    tree.append(['pmmwcg',53])
    tree.append(['agrscit',64])
    tree.append(['bfvvrgi',193])
    tree.append(['yioozfb',24])
    tree.append(['ichmv',20])
    tree.append(['jxvcmyb',137])
    tree.append(['vescu',41])
    tree.append(['ajnug',944, ['wvstx','wscmp','ritcku']])
    tree.append(['muvax',202, ['rxvyryq','spriicr','akhsran']])
    tree.append(['gyjui',82])
    tree.append(['zzsjfh',62])
    tree.append(['htwlpi',20])
    tree.append(['pnlrs',33])
    tree.append(['ifwxdp',195, ['rbmfs','pocpbk','dpyamhy']])
    tree.append(['pgwquco',39])
    tree.append(['ctixwt',201, ['sbwadli','hdnppxz']])
    tree.append(['ynnqnnu',14])
    tree.append(['kiocz',78, ['phcqjf','gncec']])
    tree.append(['rzeyzb',12])
    tree.append(['flgkko',69])
    tree.append(['jcnfvhv',25])
    tree.append(['spgebj',5477, ['liprz','sudojso','vqpkcu','qntfrg']])
    tree.append(['kjgwca',49])
    tree.append(['ppgnqem',32])
    tree.append(['zzsbho',84])
    tree.append(['tzhxfhh',186, ['nbcqjke','aaydbfp']])
    tree.append(['fbgohwn',41])
    tree.append(['zedtoui',1932, ['ggjiddn','smfpql','tmmdx']])
    tree.append(['gncec',90])
    tree.append(['emjkbw',10])
    tree.append(['hndngj',63, ['rdgfmzc','dnpap','wnlma','uggosj']])
    tree.append(['ljmmpot',65])
    tree.append(['leokcd',82])
    tree.append(['fszox',254, ['asnxgw','rvtdj']])
    tree.append(['biyngj',30])
    tree.append(['cffyru',239, ['onqtz','vipxzk']])
    tree.append(['dzimoh',56])
    tree.append(['ggvhbb',378, ['djcakxm','ghkmngk']])
    tree.append(['jkzcn',37, ['muvax','gjfhtl','tijgqz','lqgal','mchmeiz','belfq']])
    tree.append(['bpvhwhh',60, ['lzfgxlb','fzclaow','kfdxxb','xnmjpa','rilgrr','fvrrpo','zcmlgn']])
    tree.append(['khyucl',27])
    tree.append(['xnfpxnd',114, ['xvguvgw','qaktp']])
    tree.append(['unminnt',38, ['abpnn','ljihyoy']])
    tree.append(['psasli',42])
    tree.append(['pheetb',863, ['hpvubeg','zjtchm','ujudwk','xzkon']])
    tree.append(['ecviwn',268, ['kqkarm','zcqth']])
    tree.append(['axkokcp',287, ['lysjk','bxnmwa','vitgymq']])
    tree.append(['ghexz',2135, ['powvo','onqfc','hazyvie']])
    tree.append(['trunx',59])
    tree.append(['otity',59])
    tree.append(['wqvnr',78, ['mgpvr','nyeqnad']])
    tree.append(['agzekk',1759, ['ogomr','kkyycy','wqvnr']])
    tree.append(['jlnxmnt',197, ['xszevpx','ijzvrcj','dxgmc']])
    tree.append(['gvqpxq',20])
    tree.append(['dstuo',103, ['alvjlwt','qucgz','oxtumtn','wffkz']])
    tree.append(['fvrrpo',34174, ['vcedn','nfuatoz','dsknoh','jexxxx']])
    tree.append(['zhkwxu',71])
    tree.append(['ndiyxee',96, ['cjexce','xixzhx','gdhqehb']])
    tree.append(['wxrqjvy',91])
    tree.append(['owbuww',222, ['dmdxjmt','vkwfac','msdkszz']])
    tree.append(['enant',83])
    tree.append(['aosedtz',41])
    tree.append(['rssegj',27, ['mpiiw','yqznxzs','ahvumy','yycjr','iwmuonh','newnawd']])
    tree.append(['xanuprn',197, ['rveiwr','xqcvk']])
    tree.append(['fhirm',56])
    tree.append(['gxrxqy',227, ['cbeoz','xzghryr']])
    tree.append(['xjzzeu',76])
    tree.append(['gunqzbu',34, ['fqzleh','utpfhue','zzxdzzl','cithkzk']])
    tree.append(['krythkn',51])
    tree.append(['kbpdvgx',1828, ['nzokis','trdrc']])
    tree.append(['snlcnb',45, ['smxutcp','cdyfyx','itjoisx']])
    tree.append(['dszjuo',302, ['bxcfhgy','mracmcq']])
    tree.append(['rbmfs',13])
    tree.append(['dewked',96])
    tree.append(['lwwuq',30])
    tree.append(['yupgfp',53])
    tree.append(['mtpqiok',190, ['bmozv','frrsc']])
    tree.append(['zcqth',27])
    tree.append(['glyfb',98])
    tree.append(['djcakxm',33])
    tree.append(['kvmhp',52])
    tree.append(['swimi',88])
    tree.append(['dcmlo',50, ['obsmut','upfebsl','atart','etlozv']])
    tree.append(['yrobppu',9])
    tree.append(['itteaa',22, ['fveygo','wqgfmh','pksuyfu']])
    tree.append(['gotjxc',41])
    tree.append(['bvfbjdr',19, ['kyofjtt','bmrwsem','rgqohx']])
    tree.append(['zaciz',20])
    tree.append(['xouweh',148, ['vfisys','leblg','usrgham','mkxgloe']])
    tree.append(['xzkon',410, ['kipoq','nngqjua']])
    tree.append(['qnjlq',85])
    tree.append(['pgjgnaz',58])
    tree.append(['muwgzs',23])
    tree.append(['jskhzl',19, ['yhwsnv','oswlpi','ujruya','sbjuka']])
    tree.append(['qazjql',1323, ['ldxjzcc','svyuvhk','nemqds','cdvkf']])
    tree.append(['quyin',80])
    tree.append(['cdhfwg',27])
    tree.append(['mwmpp',92])
    tree.append(['jixtgz',27])
    tree.append(['gbfjjv',240, ['lvblzvy','hcpnjd','mohkqjm']])
    tree.append(['uyowaek',288, ['swscx','ytfqdj']])
    tree.append(['ekcrfnr',59])
    tree.append(['mdipga',185, ['otxfx','pybtxv']])
    tree.append(['flmfqb',62])
    tree.append(['xuglsp',95])
    tree.append(['datcnu',95])
    tree.append(['yhwsnv',89])
    tree.append(['ivcasrz',33])
    tree.append(['lgkbqm',69])
    tree.append(['nfuatoz',17, ['dgzfep','dfulw','jjwoc','pxqtr','unzfplq','lugeqg','ghexz']])
    tree.append(['vbanwb',55])
    tree.append(['oufwlo',48])
    tree.append(['ljfdk',1260, ['nudeuz','pswzpo','vifsucu']])
    tree.append(['ovggdf',80])
    tree.append(['fbhwev',2044, ['bfvvrgi','itteaa','yhpdlh']])
    tree.append(['yedhrqg',41])
    tree.append(['mqwnw',64])
    tree.append(['wseqnk',72])
    tree.append(['ozczna',89])
    tree.append(['neoaym',175, ['suyuh','xklheqv']])
    tree.append(['vbihwha',31])
    tree.append(['itmcnzc',30])
    tree.append(['sjzvkno',1469, ['xboup','mzfnhhp','ltnxno']])
    tree.append(['mxibrwp',66])
    tree.append(['ucytsw',6])
    tree.append(['abupobw',131, ['sruad','gvamy']])
    tree.append(['goyyy',169, ['zmyeh','tdhba']])
    tree.append(['jdoysh',51])
    tree.append(['llzhmol',84, ['hayenti','geuog','yhgavb','tkdal']])
    tree.append(['yvfltrt',686, ['abupobw','ltseb','ywzrkz','neoaym','aknsq','utgpz','wauprfk']])
    tree.append(['shmuahd',221, ['dxddyhh','recfc']])
    tree.append(['arldq',96, ['bfhgdou','hdbck','dworlrf','dxhgr']])
    tree.append(['wxyaro',10])
    tree.append(['udqaee',8])
    tree.append(['wpvpo',71])
    tree.append(['lytxt',70])
    tree.append(['vlcttf',375])
    tree.append(['ztoof',19])
    tree.append(['pjdbaq',17])
    tree.append(['hrkgae',15, ['datcnu','ihbwov','xjrgo']])
    tree.append(['qyfwbx',37])
    tree.append(['powvo',186, ['szfroua','seack']])
    tree.append(['ikzndn',67])
    tree.append(['wkvve',50])
    tree.append(['byfcat',58])
    tree.append(['psmylp',5])
    tree.append(['dqpng',34])
    tree.append(['ndynhq',40])
    tree.append(['dhsku',1631, ['lvrqmv','mtopo','lldbah']])
    tree.append(['mbpmp',350])
    tree.append(['tswygt',1382, ['aatuy','krcvxrb']])
    tree.append(['oqjdqhz',87])
    tree.append(['ywuie',49])
    tree.append(['xgpkw',762, ['mghjs','ekegoaj','rktbwod','vdmtlr','djvzshb']])
    tree.append(['varne',281, ['pbizn','zgqnd']])
    tree.append(['jwfem',62])
    tree.append(['bfwovd',118, ['mngbghh','eowfj']])
    tree.append(['gwowni',45])
    tree.append(['uchwojr',55, ['trsoxa','zlrfy']])
    tree.append(['sfovf',99, ['xcmjo','btfdruj','priuy']])
    tree.append(['dhdeayl',88])
    tree.append(['lfklsmy',275, ['pqkvbwc','hgwrue']])
    tree.append(['uyqbwe',54])
    tree.append(['fglno',60])
    tree.append(['klvoil',986, ['fvpns','srdaso']])
    tree.append(['sscdb',20])
    tree.append(['iqycdt',83])
    tree.append(['zqztqd',744, ['yhaja','qqomkf','dfcpcm']])
    tree.append(['uopfe',64])
    tree.append(['wxtvn',112])
    tree.append(['dlbtrjb',78])
    tree.append(['evapx',79])
    tree.append(['zpzfwgd',85])
    tree.append(['tzymfw',20])
    tree.append(['frhpgy',115, ['hqqjy','twrxos','horvahx']])
    tree.append(['kzdewu',95])
    tree.append(['vpfabxa',45])
    tree.append(['plygyiz',85])
    tree.append(['svlhbcy',80])
    tree.append(['icicush',57])
    tree.append(['bwatw',104, ['epbewj','pbinkz']])
    tree.append(['uesje',94])
    tree.append(['jnlnp',63])
    tree.append(['joduj',92])
    tree.append(['gxjbow',161, ['erjhzv','psasli']])
    tree.append(['tdsaa',56])
    tree.append(['pcsvt',49])
    tree.append(['wdrjftp',35])
    tree.append(['abqsqsw',1116, ['ksxpomr','emxlqwq','dwzeri']])
    tree.append(['lzrcpf',67])
    tree.append(['qlrshn',52, ['bnkcs','abxqias','msvagxz','gaiqlzf','cifgld','lsbzyx','qzgapj']])
    tree.append(['palhxo',82])
    tree.append(['itozwej',73])
    tree.append(['recfc',5])
    tree.append(['fnvqq',181, ['jxlak','qotrtx']])
    tree.append(['dqnif',48])
    tree.append(['saalu',47])
    tree.append(['xjrgo',95])
    tree.append(['atart',76])
    tree.append(['unegqpm',164, ['sovii','fggqv','hgbhi']])
    tree.append(['ayiitk',72])
    tree.append(['evvgx',64])
    tree.append(['pzzmg',69])
    tree.append(['raljfk',32])
    tree.append(['neiawsy',52])
    tree.append(['kkvxx',34])
    tree.append(['xvsnmmx',48, ['wdbub','kpgyfzy','kfrwdp','wpuburp']])
    tree.append(['btnoqzd',94, ['spyjrzi','rwmqr','vvsev','dstuo','wqiene','qmnsyex','skcvg']])
    tree.append(['ssurqjb',78])
    tree.append(['oxhuvih',75, ['quyin','pdbejtw']])
    tree.append(['csfac',144, ['fwkpb','thgwtgt','yuqdsv','ejggu','dporqyl','krommni','inswkfm']])
    tree.append(['zprutpl',59])
    tree.append(['pcduo',49])
    tree.append(['ahcqquf',91])
    tree.append(['vumehdr',283, ['lrewm','swtjb','epckorn']])
    tree.append(['dfulw',41, ['tdnsh','jhdhgp','iiogzk','zsxjki','ttkwrfr','eveeynr']])
    tree.append(['zjwxdsl',48, ['lmihhgo','czrjoz','bbsbwso']])
    tree.append(['brupv',74, ['vgerts','uaeeza']])
    tree.append(['zzxdzzl',88])
    tree.append(['kxrel',628, ['zedtoui','pnnwkn','ppwgp','burml']])
    tree.append(['pxqtr',2267, ['zrebihv','fukzhnf','reffy']])
    tree.append(['mgvnybx',96, ['yedeqj','lnpdxkz','pheetb','fbhwev']])
    tree.append(['llzboz',78])
    tree.append(['yknoisw',78])
    tree.append(['nbcqjke',41])
    tree.append(['ewfigm',42])
    tree.append(['nwfivan',1663, ['ljgrn','kxudhlx','kppjorc']])
    tree.append(['kfdxxb',54154, ['qhblzff','pvwsgxh','postmlp','grvzg']])
    tree.append(['oniakw',97, ['wjpdd','honkhjh']])
    tree.append(['ygsse',92])
    tree.append(['pcrxyco',20])
    tree.append(['ubxusjq',48])
    tree.append(['fiaepdw',307, ['hclfihb','cfjib']])
    tree.append(['qfkpanu',49])
    tree.append(['rkjces',41])
    tree.append(['ftbil',161])
    tree.append(['dhglkvc',95])
    tree.append(['qffyap',251, ['xuxkwp','jkkmv']])
    tree.append(['dygbnr',154, ['lkeaso','oqvygul']])
    tree.append(['vgerts',80])
    tree.append(['xsehs',55])
    tree.append(['uepkk',1821, ['spiel','zkkwvo','opwdy','bvfbjdr']])
    tree.append(['npabeh',97])
    tree.append(['fyudu',11, ['ozjskhi','ujaxyn','uyqbwe']])
    tree.append(['trsoxa',70])
    tree.append(['dtdrq',28])
    tree.append(['mbkvojh',260, ['qcodb','sjpywxy']])
    tree.append(['iwhdp',56])
    tree.append(['kqfwwv',59])
    tree.append(['qrrfj',58])
    tree.append(['yfccf',64, ['acxsu','okcbif']])
    tree.append(['gpiew',204, ['evfti','mcgydbg']])
    tree.append(['njlbp',269, ['meddd','ajebiy']])
    tree.append(['kwibs',8])
    tree.append(['gbvowdh',45])
    tree.append(['akhsran',63])
    tree.append(['wffkz',87])
    tree.append(['hyyczqe',163, ['sujgkaw','cmdkcy']])
    tree.append(['llpwnd',155, ['slhqnia','mdvfsjt']])
    tree.append(['zkdsnb',133, ['hvngmr','cesowu']])
    tree.append(['rmjqnz',276])
    tree.append(['tfjeo',48])
    tree.append(['lkeaso',52])
    tree.append(['tpqkb',184, ['ggqro','qvymrle','cqurt','ntogi','hbozd']])
    tree.append(['iiogzk',390, ['mqlgugi','upsrogz','dqtranb','vzttjf']])
    tree.append(['fnnxu',6])
    tree.append(['gvytaes',63, ['lqqdqgl','zqijwcd']])
    tree.append(['hqqjy',41])
    tree.append(['wgrdy',33, ['ctvjzip','ovxjjgk','vowidrd','hvlpcew']])
    tree.append(['ayyaq',71])
    tree.append(['jhwxxmc',79, ['ruxlsl','ghvxa','hlukdep','ozrban']])
    tree.append(['oieqvtt',63, ['oameej','ppiyhx','exwagrs']])
    tree.append(['keuxhfl',340, ['woizpm','owqobwu','lzsnst','xqnwm','oujsw']])
    tree.append(['uinbm',237, ['ejxrqp','axktcjd','xmvipsu']])
    tree.append(['aatuy',86])
    tree.append(['atdbx',17])
    tree.append(['bjkfclz',249, ['pnlrs','hyqxc']])
    tree.append(['pbmrflr',350, ['nbuie','btpwtub']])
    tree.append(['qdymjur',12])
    tree.append(['ajytayr',68])
    tree.append(['hclfihb',23])
    tree.append(['nhobovg',67])
    tree.append(['xnmjpa',72670, ['kxrel','vfjnsd','bjmzvm','mgvnybx']])
    tree.append(['ainak',1568, ['zuhwge','xhmwo','tuvdk']])
    tree.append(['kfvkh',91])
    tree.append(['jviwcde',45])
    tree.append(['tmmdx',48, ['gosft','mmjuyat']])
    tree.append(['alvjlwt',87])
    tree.append(['bdfblio',73])
    tree.append(['ekegoaj',64, ['sdzdcr','cjhaq','yslnjr','ahyhpz']])
    tree.append(['ctaxhl',25, ['tupxl','kfcucr','ghnbgge','xaycoki']])
    tree.append(['bilbbf',127, ['fxvjlr','tarlgrd','piqus']])
    tree.append(['yhpdlh',137, ['ddzbs','ykbmqm']])
    tree.append(['rveuds',34])
    tree.append(['scmer',5, ['scppxlw','zegoehg','grrjci']])
    tree.append(['uqvkdd',84])
    tree.append(['ybuimo',47])
    tree.append(['oajts',48])
    tree.append(['yxhtf',68])
    tree.append(['bhmbpei',65])
    tree.append(['cwexwaz',77])
    tree.append(['riimx',277, ['zkdsnb','rhtltex','jcyvs','dwpmy','shmuahd','zvskx','szzqsmn']])
    tree.append(['hdnppxz',15])
    tree.append(['pfiwzws',93])
    tree.append(['hksnbzc',99])
    tree.append(['ylxvd',54])
    tree.append(['eiqee',88])
    tree.append(['djdztah',18, ['kjqwac','bwszv','dutiad']])
    tree.append(['bkesn',27, ['cffyru','jvtkvxk','owbuww','njlbp','vlcttf','dppsv','jskhzl']])
    tree.append(['sbkfcbh',89])
    tree.append(['rdhwksn',24])
    tree.append(['jhylsh',51, ['fkthtxx','vqdbb','sqwjo']])
    tree.append(['tdqaege',45])
    tree.append(['vobydav',1139, ['kvdvsr','jxvcmyb','fhbbe']])
    tree.append(['nngnivo',44])
    tree.append(['lmdzx',95])
    tree.append(['xvguvgw',72])
    tree.append(['tgshzb',1457, ['fszox','qrxvqe','hrkgae']])
    tree.append(['rtlcg',91])
    tree.append(['eybms',91])
    tree.append(['xxsterg',87])
    tree.append(['jrxjdr',95])
    tree.append(['qdvmv',30])
    tree.append(['bbshy',355, ['dcmlo','mnetsv','sctwm']])
    tree.append(['bjmzvm',3517, ['blfqvmp','myqrqql','tgshzb']])
    tree.append(['evfti',25])
    tree.append(['hlukdep',76])
    tree.append(['yklbe',1599, ['fyijlyp','fhoohx','ytnhd','mzmwtg']])
    tree.append(['umheofb',94])
    tree.append(['ihciz',34])
    tree.append(['cdyfyx',14])
    tree.append(['zrebihv',62, ['ijfjve','wseqnk']])
    tree.append(['kmvyfai',79, ['lgzam','dlbtrjb']])
    tree.append(['bocgrjf',16])
    tree.append(['uzylso',85, ['vkubjgp','ovggdf']])
    tree.append(['tupxl',82])
    tree.append(['ntgxar',490, ['fzedbkl','qhinsi','ewlkda','qquge','aepgud']])
    tree.append(['yugdmgx',25])
    tree.append(['trdrc',33])
    tree.append(['lecjqrc',68])
    tree.append(['krcvxrb',86])
    tree.append(['ejxrqp',69])
    tree.append(['qtgmnht',136, ['hmocs','idhvcw']])
    tree.append(['iyjjp',65])
    tree.append(['grrjci',93])
    tree.append(['abxqias',226])
    tree.append(['wirnc',51])
    tree.append(['smjdft',77])
    tree.append(['gjfhtl',115, ['pzzmg','flgkko','xddgt','kepyvd']])
    tree.append(['kewvll',6])
    tree.append(['kribbus',91])
    tree.append(['okncqru',206, ['dewked','kggin']])
    tree.append(['ggjiddn',96, ['iprdoum','ghyax','qdvmv']])
    tree.append(['gvgfjab',83])
    tree.append(['oheqyl',60])
    tree.append(['ajebiy',53])
    tree.append(['pruiu',105, ['azegzz','trjqu']])
    tree.append(['qnmlqy',34])
    tree.append(['gqdxofo',14])
    tree.append(['ctwqys',88])
    tree.append(['mkqze',79])
    tree.append(['arxmlc',89, ['yqywtzl','zijpzl','bsdmjnd']])
    tree.append(['kddqe',1367, ['iqemusp','utmatrv','btzchz','frebmn','aejjn','qqtlw']])
    tree.append(['hjcphe',27])
    tree.append(['qusruqc',67])
    tree.append(['odpwrq',65])
    tree.append(['evemn',693, ['ttqtuts','ybtkcry','bwgyj','uubtu','vaxyae']])
    tree.append(['kiadzi',60])
    tree.append(['hzzbk',90])
    tree.append(['uylkjb',82])
    tree.append(['ypahi',73])
    tree.append(['smfpql',132, ['gwbssq','khyucl']])
    tree.append(['elndeja',76])
    tree.append(['reffy',174, ['rrcgjc','gytimq']])
    tree.append(['tnncdvi',85])
    tree.append(['yvaua',107, ['fnxgxy','fiiscny']])
    tree.append(['uokbqcq',46])
    tree.append(['yuqdsv',135, ['icicush','obohol']])
    tree.append(['tefvwb',7])
    tree.append(['qhqhx',72])
    tree.append(['ipnia',88, ['ichekvx','uepkk','agzekk','isdwz','nwfivan','ashso','niziq']])
    tree.append(['rqqcyu',71])
    tree.append(['oebbzys',2065, ['cxbcib','rpbmn','muhtyvc']])
    tree.append(['mqgxx',92])
    tree.append(['ljgrn',206, ['jvkuwnl','acdth']])
    tree.append(['hjzjhbc',53])
    tree.append(['jexxxx',13676, ['qlrshn','zqparby','etxasz','tpqkb']])
    tree.append(['zunvrg',62])
    tree.append(['hybiw',685, ['ggvhbb','fcicnl','uinbm','ckavnt','lcdnv']])
    tree.append(['zbuzek',50])
    tree.append(['jbvxahe',40])
    tree.append(['ymobi',1131, ['qsilzzo','vxnrpq','yxgken']])
    tree.append(['grvzg',55, ['roihpx','yvfltrt','odlntvv','rraaooy','otfbit','jcfix']])
    tree.append(['oxcetg',86, ['qvzryn','yjbucib']])
    tree.append(['emknkrh',47])
    tree.append(['dorcc',39])
    tree.append(['niexrb',75])
    tree.append(['nwemm',27])
    tree.append(['qntfrg',1574, ['jndpmw','pnxeoq','tujlwef']])
    tree.append(['fcfsd',95])
    tree.append(['bgteja',315])
    tree.append(['qmjdqb',9998, ['qazjql','yklbe','jkzcn']])
    tree.append(['avefgw',196, ['mrkxs','dppmh','qusruqc']])
    tree.append(['frhsix',34])
    tree.append(['tulwp',264, ['dygbnr','wufaj','oxcetg','gbfjjv','xnfpxnd','oxvjudn','anongb']])
    tree.append(['lxuwkr',16])
    tree.append(['zczzj',89])
    tree.append(['xszevpx',8])
    return tree

def calc_weight(node):
    weight = 0
    if node.children:
        for i in node.children:
            weight += calc_weight(i)
    else:
        weight = node.weight
    return weight

tree = []
tree = get_puzzle_input()

# build the initial set of nodes
node_dict = {}
for t in tree:
    n = Node(t[0], weight = t[1], carry_weight = 0, total_weight = 0)
    node_dict[t[0]] = n

# attach child nodes to parents
for t in tree:
    if len(t) > 2:
        for tt in t[2]:
            if tt in node_dict:
                node_dict[tt].parent = node_dict[t[0]]

# arrange branches in layers
# add up farthest leaves
layers = {}
for t in tree:    
    n = node_dict[t[0]]
    if n.children:
        depth = n.depth
        if depth not in layers:
            layers[depth] = []
        layers[depth].append(n.name)
    else:
        n.parent.carry_weight += n.weight        

# step through layers and total subbranches
for i in sorted(layers.iterkeys(),reverse=True):
    for j in layers[i]:
        n = node_dict[j]
        for k in n.children:
            n.carry_weight += k.total_weight
        n.total_weight = n.weight + n.carry_weight

# find bottom node
# seed unbalance-finding array
edge_2parents = {}
zero_node = False
for i in node_dict:
    ii = node_dict[i]
    if ii.children:
        edge_2parents[ii.name] = []
    if not len(ii.siblings):        
        zero_node = ii

# find unbalanced subtrees
for i in edge_2parents:
    ii = node_dict[i]
    for j in ii.children:
        if j.total_weight and j.total_weight not in edge_2parents[i]:
            edge_2parents[i].append(j.total_weight)

print 'zero node:'
print zero_node.name

# zero node = bpvhwhh

#part 2
print '------'

c = 0
max_depth = 0
max_depth_node = False
for i in edge_2parents:

    # show all subtrees with more than one total weight
    if len(edge_2parents[i]) > 1:
        c += 1
        print '{} = {}, depth {}'.format(i, edge_2parents[i], node_dict[i].depth)
        if node_dict[i].depth > max_depth:
            max_depth_node = node_dict[i]
            max_depth = node_dict[i].depth

for i in max_depth_node.children:
    print i

# bad node: vfjnsd, weight 264 is 8 over (2070 > 2062), answer is 256

